import {StoryCover} from '../StoryCover.jsx';
import React,{useState,useEffect} from 'react';
import {Art,Avatar,Button,Panel,Tag,Tabs,Modal} from './shared.jsx';
export function Following({navigate,toast,dispatch,openStory,interactions={},items=[],onUnfollow,onOpen,busy=false}){
 const [tab,setTab]=useState(`全部 ${items.length}`),[menu,setMenu]=useState(null),[removed,setRemoved]=useState([]);
 useEffect(()=>setTab(value=>value.replace(/\d+$/,String(value.startsWith('全部')?items.length:value.startsWith('等待')?items.filter(s=>!s.updated).length:items.filter(s=>s.updated).length))),[items]);
 const shown=items.filter(s=>!removed.includes(s.id)&&(!tab.startsWith('等待')||!s.updated)&&(!tab.startsWith('已有')||s.updated)&&(!tab.startsWith('最近')||s.updated));
 return <div className="d-two d-follow-page" data-screen="03"><div><Panel className="d-follow-tabs"><Tabs items={[`全部 ${items.length}`,`等待后来 ${items.filter(s=>!s.updated).length}`,`已有后来 ${items.filter(s=>s.updated).length}`,`最近更新 ${items.filter(s=>s.updated).length}`]} value={tab} onChange={setTab}/></Panel><div className="d-follow-list">{shown.map(s=><Panel className="d-follow-card" key={s.id}><StoryCover item={{...s,cover_caption:s.cover_caption||'原回答'}} className="d-follow-cover"/><div className="d-follow-copy"><Tag>{s.category||'故事'}</Tag><button className="d-story-title" onClick={()=>onOpen?onOpen(s):navigate(s.updated?'08':'02',{story:s.id})}><h2>{s.title}</h2></button><div className="d-follow-author">{s.fixture===false?<span className="d-profile-initial">{(s.author||'作').slice(0,1)}</span>:<Avatar small woman={s.id!=='career'}/>}{s.author||'原回答作者'} · {s.date||'发布时间未知'}</div><p>{s.text}</p><div className="d-follow-metrics">♧ {s.site_counts?.[0]??interactions[s.id]?.likes??0}　☏ {s.site_counts?.[1]??interactions[s.id]?.comments??0}　☆ {s.site_counts?.[2]??interactions[s.id]?.saves??0}</div></div><div className="d-follow-status"><button className={`d-status-link ${s.tone}`} onClick={()=>onOpen?onOpen(s):navigate(s.updated?'08':'02',{story:s.id})}>{s.updated?'●':'◷'}　{s.status}<span>›</span></button><div className="d-follow-reason">你更想知道：<br/><button onClick={()=>onOpen?onOpen(s):navigate('02',{story:s.id})}>⌕ {s.reason}</button></div><button className="d-more-button" aria-label={`管理关注：${s.title}`} onClick={()=>setMenu(s)}>···</button></div></Panel>)}{!shown.length&&<Panel><h3>暂时没有关注的故事</h3><Button kind="secondary" onClick={()=>navigate('01')}>去发现故事</Button></Panel>}</div></div><aside className="d-sidebar"><Panel><h3>我的关注</h3><div className="d-stat-grid"><div><b>{items.length}</b><small>关注中的故事</small></div><div><b>{items.filter(s=>s.updated).length}</b><small>已有后来</small></div></div><div className="d-blue-box"><h3>为什么关注后续？</h3><p>有些问题没有标准答案，只有时间能给出更完整的回答。关注你感兴趣的故事，当作者带来新的进展时，你会第一时间收到通知，不再错过那些「然后呢？」。</p></div></Panel><Panel className="d-follow-quote"><p>“有些故事，值得等一等。”</p><span>—— 然后呢？</span><Art sheet="03" size={[1448,1086]} crop={[964,926,101,87]}/></Panel></aside>{menu&&<Modal title="管理这则关注" kind="sheet" onClose={()=>setMenu(null)}><p>{menu.title}</p><Button kind="secondary" disabled={busy} onClick={async()=>{if(onUnfollow){await onUnfollow(menu);setMenu(null);return;}setRemoved([...removed,menu.id]);dispatch({type:'unfollow'});setMenu(null);toast('已取消这则关注（演示）');}}>取消关注</Button></Modal>}</div>;
}

