import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {Home,HomeIcon} from '../Home.jsx';
import {StoryCover} from '../StoryCover.jsx';
import {Button,Panel} from './shared.jsx';
import {SearchFilters} from './SearchFilters.jsx';
import {internalSearchUrl} from './search-model.js';
export function SearchPage({route,navigate,user,onLogin}){
 const [retry,setRetry]=useState(0);
 const [local,setLocal]=useState(null),[official,setOfficial]=useState(null),[recommended,setRecommended]=useState([]),[localError,setLocalError]=useState(''),[officialError,setOfficialError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const path=internalSearchUrl(route);
 useEffect(()=>{let active=true;setLocal(null);setLocalError('');api(path).then(data=>{if(active)setLocal(data);}).catch(e=>{if(active)setLocalError(e.message);});return()=>{active=false;};},[path,retry]);
 useEffect(()=>{let active=true;setOfficial(null);setOfficialError('');api('/discovery/search?q='+encodeURIComponent(route.q)).then(data=>{if(active)setOfficial(data);}).catch(e=>{if(active)setOfficialError(e.status===503?'知乎搜索服务暂未开放，本站搜索仍可使用。':'暂时无法取得知乎结果，请稍后重试。');});return()=>{active=false;};},[route.q,user?.id,retry]);
 useEffect(()=>{let active=true;api('/stories?limit=3').then(data=>{if(active)setRecommended(data.items);}).catch(()=>{});return()=>{active=false;};},[]);
 async function follow(item){if(!user){onLogin();return;}setBusy(true);setNotice('');try{await api(`/discovery/candidates/${item.candidate_id}/interest`,'PUT',{active:true});setNotice('已关注，后续可在“我的关注”查看。');}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 const results=<><h1 className="search-heading">“{route.q}”的搜索结果</h1><SearchFilters value={route} onChange={options=>navigate('01',options)}/><Panel><h2>本站已有内容{local?` · ${local.total}`:''}</h2>{localError?<><p role="alert">{localError}</p><Button kind="secondary" onClick={()=>setRetry(n=>n+1)}>重新搜索</Button></>:!local?<p role="status">正在搜索本站…</p>:!local.items.length?<SearchEmpty onReset={()=>navigate('01',{q:route.q})} onDiscover={()=>navigate('01')}/>:local.items.map(item=><article className="search-result" key={item.source_id}><StoryCover item={item}/><div><button className="d-story-title" onClick={()=>navigate('02',{source:item.source_id})}><h3>{item.title}</h3></button><p>{item.text}</p><small>{item.published_at?.slice(0,10)||'原发布时间未知'} · 本站可读</small></div><Button kind="soft" onClick={()=>navigate('02',{source:item.source_id})}>查看故事</Button></article>)}{local&&local.total>10&&<nav className="d-actions" aria-label="本站结果分页"><Button disabled={(Number(route.page)||1)<=1} onClick={()=>navigate('01',{...route,page:String(Number(route.page)-1)})}>上一页</Button><span>第 {Number(route.page)||1} / {Math.ceil(local.total/10)} 页</span><Button disabled={(Number(route.page)||1)*10>=local.total} onClick={()=>navigate('01',{...route,page:String((Number(route.page)||1)+1)})}>下一页</Button></nav>}</Panel><Panel><h2>知乎搜索结果</h2><p className="d-muted">官方搜索每次最多返回 10 条摘要；日期筛选仅作用于本站内容。</p>{officialError?<><p role="alert">{officialError}</p><Button kind="secondary" onClick={()=>setRetry(n=>n+1)}>重试知乎搜索</Button></>:!official?<p role="status">正在通过官方接口搜索知乎…</p>:!official.items.length?<p>这次没有找到匹配的知乎内容。</p>:official.items.map((item,i)=><article className="search-result" key={item.candidate_id||item.url||i}><StoryCover item={item}/><div><h3>{item.title}</h3><p>{item.text}</p><small>{item.author_name} · 知乎官方摘要</small><a href={item.url} target="_blank" rel="noreferrer">查看知乎原回答 ↗</a></div><Button kind="soft" disabled={busy} onClick={()=>follow(item)}>关注后续</Button></article>)}{notice&&<p role="status">{notice}</p>}</Panel></>;
 return <Home items={[]} searchMode results={results} query={route.q} onQuery={()=>{}} onSearch={()=>{}} asideExtra={recommended.length>0&&<Panel><h3>你可能也感兴趣</h3>{recommended.map(item=><button className="d-related" key={item.source_id} onClick={()=>navigate('02',{source:item.source_id})}><StoryCover item={item}/><span><b>{item.title}</b></span></button>)}</Panel>}/>;
}
export function SearchEmpty({onReset,onDiscover}){return <div className="home-empty"><div className="home-empty-art" role="img" aria-label="暂无结果插图占位"><HomeIcon name="search"/></div><h3>暂时没有符合条件的故事</h3><p>换个关键词，或去看看其他分类的故事。</p><div className="d-actions"><Button kind="secondary" onClick={onReset}>清除筛选</Button><Button kind="ghost" onClick={onDiscover}>看看其他故事</Button></div></div>;}
