import React,{useState} from 'react';
import {api,setToken} from '../api.js';
import {Button,Panel,Tabs} from './shared.jsx';
export function SessionPanel({user,onUser,onClose}){
 const [mode,setMode]=useState('真实使用'),[consent,setConsent]=useState(false);
 const [credential,setCredential]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function identify(path,body){const data=await api(path,'POST',body);setToken(data.session_token||true);onUser((await api('/me')).user);setCredential('');onClose?.();}
 return <Panel><h2>{user?'当前登录账号':'选择使用方式'}</h2>{error&&<p role="alert">{error}</p>}{user?<><p>{user.display_name||'当前账号'} · {{reader:'读者',author:'作者',researcher:'研究人员',admin:'管理员'}[user.role]||user.role}</p><p>身份由服务器确认。</p><Button disabled={busy} kind="secondary" onClick={()=>run(async()=>{await api('/auth/logout','POST');setToken(false);onUser(null);})}>退出登录</Button></>:<><Tabs items={['真实使用','体验演示','开发者']} value={mode} onChange={setMode}/>{mode==='真实使用'?<><p>先以读者身份使用本站；创作者可在“设置与资料”连接知乎，核验本人的回答后参与回访。</p><label className="d-consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意创建本站读者会话，用于保存我的关注和互动记录</label><Button disabled={busy||!consent} onClick={()=>run(()=>identify('/auth/readers',{consent:{accepted:true,version:'reader-v1'}}))}>以读者身份继续</Button></>:mode==='体验演示'?<><p>使用服务器预设的测试账号了解流程，内容为测试材料，不能进入管理后台。</p><div className="d-actions"><Button kind="secondary" disabled={busy} onClick={()=>run(()=>identify('/auth/demo/reader',{}))}>演示读者</Button><Button kind="secondary" disabled={busy} onClick={()=>run(()=>identify('/auth/demo/author',{}))}>模拟作者</Button></div></>:<form onSubmit={e=>{e.preventDefault();run(()=>identify('/auth/sessions',{login_token:credential}));}}><p>使用管理员签发的一次性凭证。是否能进入后台由服务器授予的身份决定。</p><label>一次性登录凭证<input className="d-input" type="password" autoComplete="off" value={credential} onChange={e=>setCredential(e.target.value)}/></label><Button disabled={busy||credential.length<16} type="submit">登录</Button></form>}</>}</Panel>;
}
