import React,{useEffect,useState} from 'react';
import {api,setToken} from '../api.js';
import {ZhihuAccount} from '../ZhihuAccount.jsx';
import {Panel,Button,Icon,Modal} from './shared.jsx';
import {ProfileAvatar} from '../Home.jsx';
import {Toggle} from './Account.jsx';
import {playgroundResetAllowed} from '../publish-chrome.js';
export function SettingsPage({user,onUser,onLogin,navigate}){
 const [zhihu,setZhihu]=useState(null),[memory,setMemory]=useState(null),[detail,setDetail]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setZhihu(null);setMemory(null);setError('');if(user)Promise.all([api('/me/zhihu'),api('/me/memory')]).then(([z,m])=>{if(active){setZhihu(z);setMemory(m);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[user?.id]);
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const heading=(icon,title,text)=><div className="d-account-heading"><Icon name={icon}/><div><h2>{title}</h2><p>{text}</p></div></div>;
 return <div className="d-account-settings">{notice&&<p role="status">{notice}</p>}<Panel>{heading('link','知乎账号','授权后同步可用的昵称与本人资料，无需重复填写。')}<div className="d-account-zhihu"><ProfileAvatar user={user} className="d-profile-initial" fallback="知"/><span><b>{zhihu?.display_name||user?.display_name||'尚未连接知乎账号'}</b><small>{zhihu?.authorized?'已授权':'未授权'} · {zhihu?.last_sync_at||'尚未同步'}</small></span><Button kind="secondary" onClick={()=>user?setDetail('知乎授权'):onLogin()}>{user?'管理授权':'登录并连接'}</Button></div></Panel>
 <Panel>{heading('pen','作者身份','基于自己的经历写下后来，内容始终由你确认。')}<div className="d-account-creator"><Icon name="author"/><span><b>{({author:'已核验作者身份',reader:'读者账号',admin:'管理员账号',researcher:'研究人员账号'})[user?.role]||'游客体验'}</b><small>在我的回答中查看材料、参与回访与管理发布。</small></span><Button kind="secondary" onClick={()=>navigate('05')}>我的回答 →</Button></div></Panel>
 <Panel>{heading('memory','AI 资料与记忆','从你授权的材料中整理经历和关注主题，保留可追溯的来源。')}<div className="d-account-rows">{[['me','个人资料','职业、经历与公开资料'],['calendar','人生阶段','求学、工作与生活中的阶段变化'],['star','关注主题','从经历中整理的主题，不自动建立订阅']].map(([icon,title,text])=><button key={title} onClick={()=>setDetail(title)}><Icon name={icon}/><b>{title}</b><span>{text}</span><small>{memory?.records?.length?'查看记录':'尚无记录'}　›</small></button>)}</div></Panel>
 <Panel>{heading('shield','数据使用授权','登录、材料处理与公开发布是独立的选择。')}<div className="d-account-switches"><div><Icon name="memory"/><b>AI 资料处理</b><span>仅使用已核验并授权的本人材料</span><Toggle label="AI 资料处理同意" value={memory?.enabled===true} onChange={value=>user?run(async()=>{await api('/me/memory/consent','PUT',{enabled:value});setMemory(await api('/me/memory'));}):onLogin()}/></div><div><Icon name="users"/><b>内容公开展示</b><span>在每则回答发布前单独确认</span><Button kind="ghost" onClick={()=>navigate('05')}>管理回答 ›</Button></div></div></Panel>
 {playgroundResetAllowed(user)&&<Panel>{heading('clock','刷新演示数据','评委可以一键清空演示进度，重新体验关注、问询和发布。只影响【演示】材料。')}<Button kind="secondary" disabled={busy||!user} onClick={()=>user?run(async()=>{const result=await api('/auth/demo/reset','POST',{});setNotice(`演示数据已刷新，共 ${result.stories} 则【演示】故事。`);}):onLogin()}>刷新演示数据</Button></Panel>}
 <Panel>{heading('lock','隐私与数据管理','了解资料来源，管理当前账号。')}<div className="d-account-privacy"><button onClick={()=>setDetail('资料使用说明')}><Icon name="shield"/><div><b>资料使用说明</b><small>查看来源与授权范围</small></div>›</button><button onClick={()=>user?run(async()=>{await api('/auth/logout','POST');setToken(false);onUser(null);}):onLogin()}><Icon name="logout"/><div><b>{user?'退出登录':'登录账号'}</b><small>{user?'结束当前会话':'选择真实使用或体验演示'}</small></div>›</button></div></Panel>{error&&<p role="alert">{error}</p>}
 {detail&&<Modal kind="drawer" title={detail} onClose={()=>setDetail(null)}>{detail==='知乎授权'?<ZhihuAccount/>:<><p>资料来自 OAuth 可用字段及 memU 对已授权材料的整理，不需要手动重复填写。</p>{memory?.records?.length?memory.records.map(record=><article className="d-personal-list" key={record.name}><h3>{record.name}</h3><p>{record.content}</p><small>来源：{record.source_id}</small></article>):<p className="d-blue-box">当前尚无已整理资料。连接本人账号并授权材料处理后，会在这里显示。</p>}{user&&<Button disabled={busy} onClick={()=>run(async()=>{await api('/me/memory/refresh','POST');setMemory(await api('/me/memory'));})}>刷新资料</Button>}</>}</Modal>}</div>;
}
