import React,{useState} from 'react';
import {Art,Button,Icon} from './shared.jsx';
import {HomeImage} from '../Home.jsx';
export const emptyExamples=[
 {id:'following',title:'还没有关注任何后续',body:'在这里关注你感兴趣的故事\n当有人回来更新时，你会第一时间收到通知。',button:'去发现更多故事',target:'01',crop:[163,286,173,104]},
 {id:'waiting',title:'等待作者回应',body:'你已向作者发送了回访问题，\n作者正在思考中，可能需要一些时间。',button:'查看问题',target:'02',crop:[450,285,196,107]},
 {id:'updated',title:'已有后来更新',body:'作者发布了新的后来，快去看看吧！\n时间在流动，故事仍在继续。',button:'阅读最新内容',target:'08',crop:[781,285,188,107]},
 {id:'declined',title:'作者暂不参与',body:'作者目前选择暂不参与后续回访。\n感谢你的关注，或许未来会有新的可能。',button:'去发现其他故事',target:'01',crop:[130,686,181,101]},
 {id:'withdrawn',title:'内容已撤回',body:'该内容已被作者撤回，或因其他原因\n暂时无法查看。感谢你的理解。',button:'返回上一页',target:'03',crop:[453,685,194,102]},
 {id:'timeout',title:'AI 回访暂时超时',body:'本次 AI 回访处理时间较长，可能是网络波动。\n请稍后重试，或尝试调整问题后再次发送。',button:'重新尝试',target:'06',crop:[785,681,182,106]},
 {id:'notifications',title:'暂无通知',body:'当有人回应、发布新的后来或有重要更新时，\n你会在这里收到通知。',button:'去发现故事',target:'01',crop:[1317,300,145,87]},
];
export function StateCard({example,navigate,mini=false}){return <div className={`d-empty-card ${mini?'mini':''}`} data-empty={example.id}>{mini&&<div className="d-mini-header"><b><HomeImage crop={[69,114,26,30]}/> 然后呢？</b><span>发现　我的关注　写下后来</span><Icon name="bell"/></div>}<div className="d-empty-body"><Art sheet="13" crop={example.crop} label={example.title}/><h2>{example.title}</h2><p>{example.body}</p><Button kind={['waiting','declined','withdrawn'].includes(example.id)?'secondary':'primary'} onClick={()=>navigate(example.target)}>{example.button}</Button>{example.id==='timeout'&&<Button kind="secondary" onClick={()=>navigate('06')}>调整问题</Button>}</div></div>;}
export function States({navigate}){const [selected,setSelected]=useState('following');return <div className="d-states-page" data-screen="13"><h1>状态与空态规范</h1><p className="d-muted">使用一致的视觉语言表达不同状态，保持信息清晰、层级分明、操作明确。</p><label className="d-state-select">查看状态 <select aria-label="选择空状态" value={selected} onChange={e=>setSelected(e.target.value)}>{emptyExamples.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><div className="d-state-boards"><section className="d-state-desktop"><h2>▣ 桌面端（Web）状态示例</h2><div className="d-states-gallery">{emptyExamples.slice(0,6).map((e,i)=><section key={e.id}><h3><span>{i+1}</span>{e.title}</h3><StateCard example={e} navigate={navigate} mini/></section>)}</div></section><section className="d-state-phones"><h2>▯ 移动端（Mobile）状态示例</h2><p className="d-muted">移动端保持与桌面端一致的状态表达，使用更简洁的排版和更聚焦的行动按钮，适配小屏阅读场景。</p><div>{[emptyExamples[0],emptyExamples[6],emptyExamples[3],emptyExamples[2]].map((e,i)=><section key={e.id}><h3><span>{i+1}</span>{i===0?'无关注的故事':e.title}</h3><StateCard example={e} navigate={navigate} mini/><nav>{['home','heart','author','comment','me'].map((name,j)=><button key={name} aria-label={['发现','关注','写下后来','消息','我的'][j]} onClick={()=>navigate(['01','03','05','04','09'][j])}><Icon name={name}/></button>)}</nav></section>)}</div></section></div><div className="d-mobile-state"><StateCard example={emptyExamples.find(e=>e.id===selected)} navigate={navigate}/></div></div>;}
