import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDesignState,designReducer} from './state.js';
import {designScreen,filterSamples,validZhihuUrl,restoreDraft,mobileReadingExcerpt} from './logic.js';
test('publishing requires an explicit separate consent action',()=>{assert.equal(designReducer(initialDesignState,{type:'publish'}).published,false);const consented=designReducer(initialDesignState,{type:'consent',value:true});assert.equal(designReducer(consented,{type:'publish'}).published,true);assert.equal(designReducer(consented,{type:'consent',value:false}).consent,false);assert.equal(initialDesignState.provenance,'test_fixture');});
test('paused and completed interviews cannot append answers',()=>{const paused=designReducer(initialDesignState,{type:'pause'});assert.equal(designReducer(paused,{type:'answer',value:'test'}),paused);let s=initialDesignState;for(let i=0;i<8;i++)s=designReducer(s,{type:'answer',value:`answer ${i}`});assert.equal(s.interview,5);assert.equal(s.answers.length,4);});
test('following can be reversed and read notifications are deduplicated',()=>{const followed=designReducer(initialDesignState,{type:'follow',reason:2});assert.equal(followed.reason,2);assert.equal(designReducer(followed,{type:'unfollow'}).followed,false);let s=designReducer(initialDesignState,{type:'read',id:'a'});s=designReducer(s,{type:'read',id:'a'});assert.deepEqual(s.read,['a']);assert.deepEqual(initialDesignState.read,[]);});
test('all 15 reference routes resolve; invalid route falls back to homepage',()=>{for(let i=1;i<=15;i++){const id=String(i).padStart(2,'0');assert.equal(designScreen(`?screen=${id}`),id);}for(const s of ['','?screen=16','?screen=<script>','?screen=2'])assert.equal(designScreen(s),'01');});
test('sample filters combine text, year, category and status',()=>{const rows=[['1','独立创作','作者甲','2021','职场发展','待回访'],['2','读研','作者乙','2020','学习成长','已回访']];assert.deepEqual(filterSamples(rows,'作者','全部年份','全部分类','全部状态'),rows);assert.deepEqual(filterSamples(rows,'甲','2021','职场发展','待回访'),[rows[0]]);assert.deepEqual(filterSamples(rows,'甲','2020','全部分类','全部状态'),[]);});
test('link validation rejects lookalike hosts, credentials, non-HTTPS and missing IDs',()=>{for(const url of ['https://www.zhihu.com/question/123/answer/456','https://zhuanlan.zhihu.com/p/123'])assert.equal(validZhihuUrl(url),true,url);for(const url of ['https://zhihu.com.evil.test/question/123','http://www.zhihu.com/question/123','https://user:pass@zhihu.com/question/123','https://zhihu.com/question/','bad'])assert.equal(validZhihuUrl(url),false,url);});
test('saved edits survive revisiting the draft and malformed drafts preserve fallback',()=>{const fallback={then:'原文',later:'后来',now:'回看'};assert.deepEqual(restoreDraft('{"later":"修改","now":null}',fallback),{then:'原文',later:'修改',now:'回看'});assert.deepEqual(restoreDraft('broken',fallback),fallback);assert.deepEqual(restoreDraft('null',fallback),fallback);});

test('mobile reading uses the reference excerpt without changing the desktop source',()=>{const source='第一段\n第二段\n第三段';assert.equal(mobileReadingExcerpt(source,0),'第一段第二段第三段');assert.equal(mobileReadingExcerpt(source,1),'第一段第二段');assert.ok(mobileReadingExcerpt(source,2).endsWith('自己……'));assert.equal(source,'第一段\n第二段\n第三段');});
