import {followedStories} from './Following.jsx';
import {StoryCover} from '../StoryCover.jsx';
import React,{useState} from 'react';
import {AvatarGroup,Author,Button,Tag,Panel,Metrics,Art,Icon,Modal,OriginalStory,storyTitle,storyParagraphs} from './shared.jsx';
import {HomeImage} from '../Home.jsx';
export const reasons=[['现在的结果与变化','后来过得怎么样了？\n是否实现了当初的想法？'],['过程中的转折与经历','这期间遇到了什么困难？\n有哪些重要的转折点？'],['回头看的感受与建议','现在如何看待这段经历？\n有什么经验教训？'],['其他，我想补充','我有其他好奇的问题…']];
export function ReasonChoices({value,onChange}){return <div className="d-reasons">{reasons.map(([title,detail],i)=><label key={title} className={value===i?'selected':''}><input type="radio" name="reason" checked={value===i} onChange={()=>onChange(i)}/><span><b>{title}</b><small>{detail}</small></span></label>)}</div>;}
export function Story({navigate,state={},dispatch=()=>{},toast=()=>{},engagement,onSearchTopic,story,followSlot,recommendations}){
 const [reason,setReason]=useState(0),[expanded,setExpanded]=useState(false),[original,setOriginal]=useState(false);
 const item=story||{id:'career',title:storyTitle,category:'职场发展',author:'林下的风',date:'2021-06-12',text:storyParagraphs.join('\n\n')};
 const paragraphs=(item.text||'正文暂未提供。').split(/\n+/).filter(Boolean);
 const interest=followSlot||<div className="d-interest"><h2><HomeImage crop={[69,114,26,30]}/>然后呢？</h2><p className="d-interest-intro">想知道这段经历后来发生了什么吗？</p><b>你更想知道什么？</b><ReasonChoices value={reason} onChange={setReason}/>{reason===3&&<textarea className="d-input" aria-label="补充问题" placeholder="写下你想了解的后来…"/>}<Button className="wide" onClick={()=>{dispatch({type:state.followed?'unfollow':'follow',reason});toast(state.followed?'已取消这则关注（体验）':'已记录关注偏好（体验）');}}>{state.followed?'取消关注':'关注后续'}</Button></div>;
 return <div className="d-two d-story-page" data-screen="02"><Panel className="d-story-main"><Tag>{item.category||'故事'}</Tag><h1>{item.title}</h1><div className="d-story-meta"><span>{item.date||item.published_at?.slice(0,10)||'发布时间未知'} · 原回答</span>{item.original_url?<a href={item.original_url} target="_blank" rel="noreferrer">查看原回答 ↗</a>:<button className="d-link" onClick={()=>setOriginal(true)}>查看原回答 ↗</button>}</div><div className="d-author"><span className="d-profile-initial">{(item.author||'作').slice(0,1)}</span><b>{item.author||'原回答作者'}</b></div><div className={`d-story-body ${expanded?'expanded':''}`}>{paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div><button className="d-expand" onClick={()=>setExpanded(!expanded)}>{expanded?'收起全文⌃':'展开全部⌄'}</button>{engagement?React.cloneElement(engagement,{afterToolbar:interest}):interest}</Panel><aside className="d-sidebar"><Panel><h3>故事信息</h3><div className="d-info-box"><p><Icon name="calendar"/>发布时间 <span>{item.date||item.published_at?.slice(0,10)||'未知'}</span></p><p><Icon name="book"/>来源 <span>原回答</span></p><p><Icon name="shield"/>状态 <Tag tone={item.updated?'green':'orange'}>{item.updated?'已有后来':'等待后来'}</Tag></p></div><div className="d-blue-box"><h3>每段经历，都有后来</h3><p>关注这段经历，让时间补充当时的答案。</p></div></Panel><Panel><h3>相关话题</h3><div className="d-tags">{(item.tags||[item.category||'人生经历']).map(t=><button className="d-tag blue" key={t} onClick={()=>onSearchTopic?onSearchTopic(t):navigate('01',{q:t})}># {t}</button>)}</div></Panel><Panel><h3>你可能也感兴趣</h3>{recommendations||(item.source_id?<Button kind="soft" onClick={()=>navigate('01')}>发现更多故事 →</Button>:followedStories.filter(s=>s.id!==item.id).slice(0,3).map(s=><button className="d-related" key={s.id} onClick={()=>navigate('02',{story:s.id})}><StoryCover item={s}/><span><b>{s.title}</b><small>{s.category} · 设计示例</small></span></button>))}</Panel></aside>{original&&<Modal title="原回答" onClose={()=>setOriginal(false)}><h3>{item.title}</h3>{paragraphs.map((p,i)=><p key={i}>{p}</p>)}<small>{item.source_id?'原始外链未提供，以上为本站可展示的材料。':'当前为体验材料；原始外链未提供。'}</small></Modal>}</div>;
}
