import React,{useState} from 'react';
import {Art,AvatarGroup,Button,Panel,Tabs,Icon} from './shared.jsx';
import {WorkbenchCard} from './WorkbenchCard.jsx';
import {ParticipationDialog} from './ParticipationDialog.jsx';
import {followedStories} from './Following.jsx';
export function Workbench({navigate,state,initialTab,content}){
 const [invite,setInvite]=useState(null);
 const [tab,setTab]=useState(initialTab||'等我回应 3');
 return <div className="d-workbench" data-screen="05"><section className="d-work-hero"><div><h1>那些你曾认真写下的回答，<br/>值得一个后来。</h1><p>时光已经走过很远，现在，轮到你继续讲述。</p></div><Art sheet="05" size={[1448,1086]} crop={[506,176,504,167]} label="过去的回答是一个起点，而现在的你拥有了新的答案"/></section><div className="d-two"><div>{content??<><Tabs items={['等我回应 3','正在写 2',`已发布 ${state.published?6:5}`]} value={tab} onChange={setTab}/>{followedStories.slice(0,tab.startsWith('正在')?2:3).map((s,i)=><WorkbenchCard key={s.id} third={i===2} card={{...s,fixture:true,crop:[[63,433,116,116],[63,661,116,109],[63,872,116,115]][i],meta:`${s.date} · ${s.category} · 公开回答`,excerpt:i===0?'我在大厂工作了五年，收入稳定，但总觉得自己像一颗螺丝钉。上周我提交了辞职申请，准备给自己半年的时间……':s.text,interestCount:[214,178,96][i],reasons:['结果与变化','转折与经历','回头看'].map((label,n)=>({label,percentage:[[46,31,23],[52,28,20],[38,42,20]][i][n]})),action:{label:tab.startsWith('正在')?'继续写后来':tab.startsWith('已发布')?'查看已发布的后来':'愿意讲讲后来吗？'}}} onAction={()=>tab.startsWith('等我')?setInvite(s):navigate(tab.startsWith('已发布')?'08':'06',{story:s.id})}/>)}</>}</div><aside className="d-sidebar"><Panel><h3>为什么是你来写后来？</h3>{[['me','只有你最了解那段经历','这段经历源于你真实的生活，也只有你知道后来的答案。'],['heart','你的后续能帮助很多人',content?'关注你故事的读者，也在等待你的更新。':'214 位读者正在关注这个故事，他们也在等待你的更新。'],['pen','这是一次与过去的自己对话','写下后来的过程，也是重新认识自己、看见成长的机会。']].map(([icon,title,text])=><div className="d-principle" key={title}><Icon name={icon}/><div><b>{title}</b><p>{text}</p></div></div>)}<div className="d-work-quote"><p>“每一个认真生活的人，<br/>都值得被时间好好回答。”</p><span>—— 然后呢？</span><Art sheet="05" size={[1448,1086]} crop={[913,719,115,71]}/></div></Panel><Panel><h3>我们的原则</h3>{[['document','由作者亲自补充','确保内容的真实性与个人视角'],['ai','AI 辅助采访与整理','帮你梳理思路、生成提纲，不代写'],['lock','可随时修改或设为私密','在发布前，你始终拥有完全的控制权']].map(([icon,title,text])=><div className="d-principle compact" key={title}><Icon name={icon}/><div><b>{title}</b><p>{text}</p></div></div>)}</Panel></aside></div>{invite&&<ParticipationDialog title={invite.title} onClose={()=>setInvite(null)} onStart={()=>{setInvite(null);navigate('06',{story:invite.id});}}/>}</div>;
}
