CREATE TABLE "cover_catalog" (
	"id" text PRIMARY KEY NOT NULL,
	"category" text NOT NULL,
	"tags" jsonb NOT NULL,
	"alt" text NOT NULL,
	"source_url" text,
	"image_url" text,
	"status" text DEFAULT 'pending_asset' NOT NULL
);

--> statement-breakpoint
INSERT INTO "cover_catalog" ("id","category","tags","alt","source_url","image_url","status") VALUES
('CF001','职场发展','["职场发展", "通用留白"]'::jsonb,'Laptop on a desk with creative work displayed, in a cozy and well-lit space','https://www.pexels.com/photo/laptop-on-a-desk-26648986/',NULL,'pending_asset'),
('CF002','职场发展','["职场发展", "通用留白"]'::jsonb,'Comfortable home office setup featuring a laptop, house plants, and stationery on a wooden desk','https://www.pexels.com/photo/laptop-on-desk-7888648/',NULL,'pending_asset'),
('CF003','职场发展','["职场发展", "通用留白"]'::jsonb,'A sleek laptop on a pristine desk in a contemporary open office space','https://www.pexels.com/photo/laptop-on-desk-in-office-17367708/',NULL,'pending_asset'),
('CF004','职场发展','["职场发展", "通用留白"]'::jsonb,'Elegant desk setup with laptop and monitor, perfect for tech and workspace themes','https://www.pexels.com/photo/laptop-on-desk-24790756/',NULL,'pending_asset'),
('CF005','人生选择','["人生选择", "迁移旅行"]'::jsonb,'A serene drive along a winding road with mountains and lush vegetation in the background','https://www.pexels.com/photo/scenic-road-amongst-mountainous-landscape-37194779/',NULL,'pending_asset'),
('CF006','学习成长','["学习成长", "同伴支持"]'::jsonb,'Three students engaged in studying in a library surrounded by bookshelves, enhancing academic learning','https://www.pexels.com/photo/three-college-students-in-the-library-9572550/',NULL,'pending_asset'),
('CF007','学习成长','["学习成长", "同伴支持"]'::jsonb,'Two students study together at a library desk with a laptop and books','https://www.pexels.com/photo/students-studying-at-the-library-6281016/',NULL,'pending_asset'),
('CF008','学习成长','["学习成长", "同伴支持"]'::jsonb,'Students studying together at a library with laptops and books','https://www.pexels.com/photo/students-studying-at-the-library-6281030/',NULL,'pending_asset'),
('CF009','学习成长','["学习成长", "同伴支持"]'::jsonb,'Students studying in a contemporary library with glass walls, desks, and shelves','https://www.pexels.com/photo/students-in-library-4903651/',NULL,'pending_asset'),
('CF010','学习成长','["学习成长", "同伴支持"]'::jsonb,'A young woman and man study together at a library table, focused on their notes','https://www.pexels.com/photo/students-studying-intently-in-a-modern-library-35545154/',NULL,'pending_asset'),
('CF011','情感关系','["情感关系", "城市生活"]'::jsonb,'A couple sharing a bonding moment while reading indoors, promoting love and togetherness','https://www.pexels.com/photo/photo-of-couple-spending-time-together-7188676/',NULL,'pending_asset'),
('CF012','情感关系','["情感关系", "城市生活"]'::jsonb,'A happy couple embraces on a sunlit balcony with stylish architecture, enjoying a bright day','https://www.pexels.com/photo/city-man-people-woman-13114575/',NULL,'pending_asset'),
('CF013','情感关系','["情感关系", "城市生活"]'::jsonb,'A loving couple laughing together while embracing by the seaside','https://www.pexels.com/photo/laughing-couple-on-a-beach-20784260/',NULL,'pending_asset'),
('CF014','创业思考','["创业思考", "通用留白"]'::jsonb,'A thoughtful businessman in a red shirt sits at a desk with a laptop and tablet, deep in thought','https://www.pexels.com/photo/pensive-businessman-at-desk-15545299/',NULL,'pending_asset'),
('CF015','创业思考','["创业思考", "通用留白"]'::jsonb,'Laptop on office desk with a city skyline through a large window, offering a modern workspace view','https://www.pexels.com/photo/laptop-on-a-desk-5483188/',NULL,'pending_asset'),
('CF016','创业思考','["创业思考", "通用留白"]'::jsonb,'Minimalist workspace featuring a laptop, AirPods, and pen holder on a wooden desk','https://www.pexels.com/photo/laptop-on-wooden-desk-4013230/',NULL,'pending_asset'),
('CF017','家庭亲情','["家庭亲情", "温暖居家"]'::jsonb,'A family sharing a joyful moment inside their cozy, traditionally decorated home','https://www.pexels.com/photo/warm-family-moment-in-traditional-home-37299401/',NULL,'pending_asset'),
('CF018','家庭亲情','["家庭亲情", "温暖居家"]'::jsonb,'Warm family dinner with candles and wine, perfect for intimate home gatherings','https://www.pexels.com/photo/family-having-dinner-at-home-11368703/',NULL,'pending_asset'),
('CF019','职场发展','["职场发展", "创业思考", "通用留白", "远程办公"]'::jsonb,'极简办公桌上的笔记本与记事本，适合“转行、求职、第一份工作”',NULL,NULL,'pending_asset'),
('CF020','职场发展','["职场发展", "面试求职"]'::jsonb,'现代开放式办公室中的空工位，适合“职业规划、升职跳槽”',NULL,NULL,'pending_asset'),
('CF021','职场发展','["职场发展", "通用留白", "办公室"]'::jsonb,'窗边远程办公桌面，适合“自由职业、居家办公”',NULL,NULL,'pending_asset'),
('CF022','职场发展','["职场发展", "创业思考", "桌面工作台"]'::jsonb,'夜晚加班工作台，适合“职场压力、成长阵痛”',NULL,NULL,'pending_asset'),
('CF023','职场发展','["职场发展", "通用留白", "晋升成长"]'::jsonb,'两人会议桌沟通场景，适合“面试复盘、团队协作”',NULL,NULL,'pending_asset'),
('CF024','职场发展','["职场发展", "转行思考"]'::jsonb,'简洁显示器与键盘的产品工作台，适合“做项目、实习经历”',NULL,NULL,'pending_asset'),
('CF025','职场发展','["职场发展", "创业思考", "通用留白", "协作会议"]'::jsonb,'会议室玻璃反射中的人影，适合“进入大厂、职业选择”',NULL,NULL,'pending_asset'),
('CF026','职场发展','["职场发展", "加班夜晚"]'::jsonb,'咖啡馆工作场景，适合“副业、远程接单”',NULL,NULL,'pending_asset'),
('CF027','职场发展','["职场发展", "通用留白", "远程办公"]'::jsonb,'极简办公桌上的笔记本与记事本，适合“转行、求职、第一份工作”',NULL,NULL,'pending_asset'),
('CF028','职场发展','["职场发展", "创业思考", "面试求职"]'::jsonb,'现代开放式办公室中的空工位，适合“职业规划、升职跳槽”',NULL,NULL,'pending_asset'),
('CF029','职场发展','["职场发展", "通用留白", "办公室"]'::jsonb,'窗边远程办公桌面，适合“自由职业、居家办公”',NULL,NULL,'pending_asset'),
('CF030','职场发展','["职场发展", "桌面工作台"]'::jsonb,'夜晚加班工作台，适合“职场压力、成长阵痛”',NULL,NULL,'pending_asset'),
('CF031','职场发展','["职场发展", "创业思考", "通用留白", "晋升成长"]'::jsonb,'两人会议桌沟通场景，适合“面试复盘、团队协作”',NULL,NULL,'pending_asset'),
('CF032','职场发展','["职场发展", "转行思考"]'::jsonb,'简洁显示器与键盘的产品工作台，适合“做项目、实习经历”',NULL,NULL,'pending_asset'),
('CF033','职场发展','["职场发展", "通用留白", "协作会议"]'::jsonb,'会议室玻璃反射中的人影，适合“进入大厂、职业选择”',NULL,NULL,'pending_asset'),
('CF034','职场发展','["职场发展", "创业思考", "加班夜晚"]'::jsonb,'咖啡馆工作场景，适合“副业、远程接单”',NULL,NULL,'pending_asset'),
('CF035','人生选择','["人生选择", "迁移旅行", "自我反思", "公路远方"]'::jsonb,'山路或公路向远方延伸，适合“离开、重新开始、重大决定”',NULL,NULL,'pending_asset'),
('CF036','人生选择','["人生选择", "路口抉择"]'::jsonb,'站在路口或岔路前的人物背影，适合“选择困难、人生岔路”',NULL,NULL,'pending_asset'),
('CF037','人生选择','["人生选择", "迁移旅行", "窗边沉思"]'::jsonb,'窗边沉思的单人场景，适合“我该怎么办、纠结与反思”',NULL,NULL,'pending_asset'),
('CF038','人生选择','["人生选择", "城市离开"]'::jsonb,'带行李箱的出发时刻，适合“搬家、去别的城市”',NULL,NULL,'pending_asset'),
('CF039','人生选择','["人生选择", "迁移旅行", "自我反思", "山路旅途"]'::jsonb,'高铁站或站台等待，适合“告别过去、奔赴未来”',NULL,NULL,'pending_asset'),
('CF040','人生选择','["人生选择", "重新开始"]'::jsonb,'晨雾山景与道路，适合“迷茫后重新出发”',NULL,NULL,'pending_asset'),
('CF041','人生选择','["人生选择", "迁移旅行", "站台出发"]'::jsonb,'山路或公路向远方延伸，适合“离开、重新开始、重大决定”',NULL,NULL,'pending_asset'),
('CF042','人生选择','["人生选择", "公路远方"]'::jsonb,'站在路口或岔路前的人物背影，适合“选择困难、人生岔路”',NULL,NULL,'pending_asset'),
('CF043','人生选择','["人生选择", "迁移旅行", "自我反思", "路口抉择"]'::jsonb,'窗边沉思的单人场景，适合“我该怎么办、纠结与反思”',NULL,NULL,'pending_asset'),
('CF044','人生选择','["人生选择", "窗边沉思"]'::jsonb,'带行李箱的出发时刻，适合“搬家、去别的城市”',NULL,NULL,'pending_asset'),
('CF045','人生选择','["人生选择", "迁移旅行", "城市离开"]'::jsonb,'高铁站或站台等待，适合“告别过去、奔赴未来”',NULL,NULL,'pending_asset'),
('CF046','人生选择','["人生选择", "山路旅途"]'::jsonb,'晨雾山景与道路，适合“迷茫后重新出发”',NULL,NULL,'pending_asset'),
('CF047','人生选择','["人生选择", "迁移旅行", "自我反思", "重新开始"]'::jsonb,'山路或公路向远方延伸，适合“离开、重新开始、重大决定”',NULL,NULL,'pending_asset'),
('CF048','人生选择','["人生选择", "站台出发"]'::jsonb,'站在路口或岔路前的人物背影，适合“选择困难、人生岔路”',NULL,NULL,'pending_asset'),
('CF049','学习成长','["学习成长", "自我反思", "职场发展", "图书馆学习"]'::jsonb,'图书馆双人学习桌，适合“考研、期末、互相鼓励”',NULL,NULL,'pending_asset'),
('CF050','学习成长','["学习成长", "自习室"]'::jsonb,'自习室夜晚台灯与教材，适合“长期坚持、自律成长”',NULL,NULL,'pending_asset'),
('CF051','学习成长','["学习成长", "双人学习"]'::jsonb,'校园步道上的学生背影，适合“大学生活、成长记录”',NULL,NULL,'pending_asset'),
('CF052','学习成长','["学习成长", "自我反思", "考试备战"]'::jsonb,'课堂讨论或小组学习，适合“课程项目、竞赛合作”',NULL,NULL,'pending_asset'),
('CF053','学习成长','["学习成长", "职场发展", "笔记书桌"]'::jsonb,'书桌、手写笔记与电脑，适合“学习方法、经验分享”',NULL,NULL,'pending_asset'),
('CF054','学习成长','["学习成长", "校园步道"]'::jsonb,'现代图书馆安静阅读，适合“沉浸学习、查资料”',NULL,NULL,'pending_asset'),
('CF055','学习成长','["学习成长", "自我反思", "课堂讨论"]'::jsonb,'备考焦虑但专注的单人场景，适合“高考、考公、考研”',NULL,NULL,'pending_asset'),
('CF056','学习成长','["学习成长", "夜读"]'::jsonb,'图书馆双人学习桌，适合“考研、期末、互相鼓励”',NULL,NULL,'pending_asset'),
('CF057','学习成长','["学习成长", "职场发展", "图书馆学习"]'::jsonb,'自习室夜晚台灯与教材，适合“长期坚持、自律成长”',NULL,NULL,'pending_asset'),
('CF058','学习成长','["学习成长", "自我反思", "自习室"]'::jsonb,'校园步道上的学生背影，适合“大学生活、成长记录”',NULL,NULL,'pending_asset'),
('CF059','学习成长','["学习成长", "双人学习"]'::jsonb,'课堂讨论或小组学习，适合“课程项目、竞赛合作”',NULL,NULL,'pending_asset'),
('CF060','学习成长','["学习成长", "考试备战"]'::jsonb,'书桌、手写笔记与电脑，适合“学习方法、经验分享”',NULL,NULL,'pending_asset'),
('CF061','学习成长','["学习成长", "自我反思", "职场发展", "笔记书桌"]'::jsonb,'现代图书馆安静阅读，适合“沉浸学习、查资料”',NULL,NULL,'pending_asset'),
('CF062','学习成长','["学习成长", "校园步道"]'::jsonb,'备考焦虑但专注的单人场景，适合“高考、考公、考研”',NULL,NULL,'pending_asset'),
('CF063','学习成长','["学习成长", "课堂讨论"]'::jsonb,'图书馆双人学习桌，适合“考研、期末、互相鼓励”',NULL,NULL,'pending_asset'),
('CF064','情感关系','["情感关系", "家庭亲情", "城市生活", "情侣沟通"]'::jsonb,'两人在室内并肩阅读或交谈，适合“恋爱沟通、关系经营”',NULL,NULL,'pending_asset'),
('CF065','情感关系','["情感关系", "并肩独处"]'::jsonb,'阳台或窗边拥抱，适合“重逢、和解、陪伴”',NULL,NULL,'pending_asset'),
('CF066','情感关系','["情感关系", "和解拥抱"]'::jsonb,'海边或公园漫步，适合“恋爱、告白、相处日常”',NULL,NULL,'pending_asset'),
('CF067','情感关系','["情感关系", "家庭亲情", "海边相伴"]'::jsonb,'同一空间中的轻微疏离感，适合“分手、冷战、情感困惑”',NULL,NULL,'pending_asset'),
('CF068','情感关系','["情感关系", "城市生活", "居家陪伴"]'::jsonb,'餐桌对坐或咖啡馆交流，适合“关系讨论、坦白局”',NULL,NULL,'pending_asset'),
('CF069','情感关系','["情感关系", "关系疏离"]'::jsonb,'背影式双人画面，适合“婚姻、陪伴、长期关系”',NULL,NULL,'pending_asset'),
('CF070','情感关系','["情感关系", "家庭亲情", "约会散步"]'::jsonb,'独处后望向对方的场景，适合“失恋、挽回、情绪波动”',NULL,NULL,'pending_asset'),
('CF071','情感关系','["情感关系", "窗边对望"]'::jsonb,'两人在室内并肩阅读或交谈，适合“恋爱沟通、关系经营”',NULL,NULL,'pending_asset'),
('CF072','情感关系','["情感关系", "城市生活", "情侣沟通"]'::jsonb,'阳台或窗边拥抱，适合“重逢、和解、陪伴”',NULL,NULL,'pending_asset'),
('CF073','情感关系','["情感关系", "家庭亲情", "并肩独处"]'::jsonb,'海边或公园漫步，适合“恋爱、告白、相处日常”',NULL,NULL,'pending_asset'),
('CF074','情感关系','["情感关系", "和解拥抱"]'::jsonb,'同一空间中的轻微疏离感，适合“分手、冷战、情感困惑”',NULL,NULL,'pending_asset'),
('CF075','情感关系','["情感关系", "海边相伴"]'::jsonb,'餐桌对坐或咖啡馆交流，适合“关系讨论、坦白局”',NULL,NULL,'pending_asset'),
('CF076','情感关系','["情感关系", "家庭亲情", "城市生活", "居家陪伴"]'::jsonb,'背影式双人画面，适合“婚姻、陪伴、长期关系”',NULL,NULL,'pending_asset'),
('CF077','情感关系','["情感关系", "关系疏离"]'::jsonb,'独处后望向对方的场景，适合“失恋、挽回、情绪波动”',NULL,NULL,'pending_asset'),
('CF078','情感关系','["情感关系", "约会散步"]'::jsonb,'两人在室内并肩阅读或交谈，适合“恋爱沟通、关系经营”',NULL,NULL,'pending_asset'),
('CF079','情感关系','["情感关系", "家庭亲情", "窗边对望"]'::jsonb,'阳台或窗边拥抱，适合“重逢、和解、陪伴”',NULL,NULL,'pending_asset'),
('CF080','情感关系','["情感关系", "城市生活", "情侣沟通"]'::jsonb,'海边或公园漫步，适合“恋爱、告白、相处日常”',NULL,NULL,'pending_asset'),
('CF081','创业思考','["创业思考", "职场发展", "通用留白", "创始人沉思"]'::jsonb,'创始人独自坐在桌前思考，适合“创业想法、商业判断”',NULL,NULL,'pending_asset'),
('CF082','创业思考','["创业思考", "极简工作台"]'::jsonb,'白板与便利贴的讨论角落，适合“产品规划、团队方向”',NULL,NULL,'pending_asset'),
('CF083','创业思考','["创业思考", "职场发展", "白板讨论"]'::jsonb,'极简工作台与原型草图，适合“从想法到产品”',NULL,NULL,'pending_asset'),
('CF084','创业思考','["创业思考", "产品草图"]'::jsonb,'夜间办公室与电脑屏幕，适合“熬夜开发、项目冲刺”',NULL,NULL,'pending_asset'),
('CF085','创业思考','["创业思考", "职场发展", "夜间办公"]'::jsonb,'小团队围桌交流，适合“合伙人、协作、创业初期”',NULL,NULL,'pending_asset'),
('CF086','创业思考','["创业思考", "通用留白", "城市办公室"]'::jsonb,'城市景观旁的办公桌，适合“融资、未来想象、扩张”',NULL,NULL,'pending_asset'),
('CF087','创业思考','["创业思考", "职场发展", "小团队协作"]'::jsonb,'创始人独自坐在桌前思考，适合“创业想法、商业判断”',NULL,NULL,'pending_asset'),
('CF088','创业思考','["创业思考", "创始人沉思"]'::jsonb,'白板与便利贴的讨论角落，适合“产品规划、团队方向”',NULL,NULL,'pending_asset'),
('CF089','创业思考','["创业思考", "职场发展", "极简工作台"]'::jsonb,'极简工作台与原型草图，适合“从想法到产品”',NULL,NULL,'pending_asset'),
('CF090','创业思考','["创业思考", "白板讨论"]'::jsonb,'夜间办公室与电脑屏幕，适合“熬夜开发、项目冲刺”',NULL,NULL,'pending_asset'),
('CF091','创业思考','["创业思考", "职场发展", "通用留白", "产品草图"]'::jsonb,'小团队围桌交流，适合“合伙人、协作、创业初期”',NULL,NULL,'pending_asset'),
('CF092','创业思考','["创业思考", "夜间办公"]'::jsonb,'城市景观旁的办公桌，适合“融资、未来想象、扩张”',NULL,NULL,'pending_asset'),
('CF093','家庭亲情','["家庭亲情", "情感关系", "家庭晚餐"]'::jsonb,'家庭餐桌的温暖时刻，适合“回家、节日、亲情修复”',NULL,NULL,'pending_asset'),
('CF094','家庭亲情','["家庭亲情", "亲子陪伴"]'::jsonb,'客厅沙发上的亲子陪伴，适合“教育、成长、陪伴”',NULL,NULL,'pending_asset'),
('CF095','家庭亲情','["家庭亲情", "多代同堂"]'::jsonb,'多代同堂合影感场景，适合“家庭责任、孝顺、传统”',NULL,NULL,'pending_asset'),
('CF096','家庭亲情','["家庭亲情", "客厅交流"]'::jsonb,'厨房或家务场景，适合“照料家人、日常生活”',NULL,NULL,'pending_asset'),
('CF097','家庭亲情','["家庭亲情", "情感关系", "回家时刻"]'::jsonb,'门口迎接或送别，适合“离家、归来、牵挂”',NULL,NULL,'pending_asset'),
('CF098','家庭亲情','["家庭亲情", "家庭照料"]'::jsonb,'长辈与年轻人交谈，适合“代际沟通、家庭选择”',NULL,NULL,'pending_asset'),
('CF099','家庭亲情','["家庭亲情", "节日团聚"]'::jsonb,'家庭餐桌的温暖时刻，适合“回家、节日、亲情修复”',NULL,NULL,'pending_asset'),
('CF100','家庭亲情','["家庭亲情", "家庭晚餐"]'::jsonb,'客厅沙发上的亲子陪伴，适合“教育、成长、陪伴”',NULL,NULL,'pending_asset'),
('CF101','家庭亲情','["家庭亲情", "情感关系", "亲子陪伴"]'::jsonb,'多代同堂合影感场景，适合“家庭责任、孝顺、传统”',NULL,NULL,'pending_asset'),
('CF102','家庭亲情','["家庭亲情", "多代同堂"]'::jsonb,'厨房或家务场景，适合“照料家人、日常生活”',NULL,NULL,'pending_asset'),
('CF103','家庭亲情','["家庭亲情", "客厅交流"]'::jsonb,'门口迎接或送别，适合“离家、归来、牵挂”',NULL,NULL,'pending_asset'),
('CF104','家庭亲情','["家庭亲情", "回家时刻"]'::jsonb,'长辈与年轻人交谈，适合“代际沟通、家庭选择”',NULL,NULL,'pending_asset'),
('CF105','家庭亲情','["家庭亲情", "情感关系", "家庭照料"]'::jsonb,'家庭餐桌的温暖时刻，适合“回家、节日、亲情修复”',NULL,NULL,'pending_asset'),
('CF106','城市生活','["城市生活", "自我反思", "地铁通勤"]'::jsonb,'地铁车厢或站台等待，适合“通勤、北漂沪漂、节奏”',NULL,NULL,'pending_asset'),
('CF107','城市生活','["城市生活", "窗外夜景"]'::jsonb,'夜晚窗外城市灯光，适合“大城市孤独、奋斗”',NULL,NULL,'pending_asset'),
('CF108','城市生活','["城市生活", "自我反思", "街头步行"]'::jsonb,'咖啡馆独处与街景，适合“城市日常、轻生活”',NULL,NULL,'pending_asset'),
('CF109','城市生活','["城市生活", "咖啡馆独处"]'::jsonb,'步行街背影或斑马线，适合“转场、生活记录”',NULL,NULL,'pending_asset'),
('CF110','城市生活','["城市生活", "自我反思", "城市天际线"]'::jsonb,'出租屋一角，适合“独居、工作与生活平衡”',NULL,NULL,'pending_asset'),
('CF111','城市生活','["城市生活", "出租屋日常"]'::jsonb,'地铁车厢或站台等待，适合“通勤、北漂沪漂、节奏”',NULL,NULL,'pending_asset'),
('CF112','城市生活','["城市生活", "自我反思", "地铁通勤"]'::jsonb,'夜晚窗外城市灯光，适合“大城市孤独、奋斗”',NULL,NULL,'pending_asset'),
('CF113','城市生活','["城市生活", "窗外夜景"]'::jsonb,'咖啡馆独处与街景，适合“城市日常、轻生活”',NULL,NULL,'pending_asset'),
('CF114','城市生活','["城市生活", "自我反思", "街头步行"]'::jsonb,'步行街背影或斑马线，适合“转场、生活记录”',NULL,NULL,'pending_asset'),
('CF115','城市生活','["城市生活", "咖啡馆独处"]'::jsonb,'出租屋一角，适合“独居、工作与生活平衡”',NULL,NULL,'pending_asset'),
('CF116','自我反思','["自我反思", "独处沉思"]'::jsonb,'单人窗边发呆，适合“内耗、迷茫、自我和解”',NULL,NULL,'pending_asset'),
('CF117','自我反思','["自我反思", "窗边发呆"]'::jsonb,'空房间与一把椅子，适合“失落、留白、重新整理自己”',NULL,NULL,'pending_asset'),
('CF118','自我反思','["自我反思", "空房间"]'::jsonb,'夜晚台灯与书桌，适合“深夜思考、情绪记录”',NULL,NULL,'pending_asset'),
('CF119','自我反思','["自我反思", "夜晚台灯"]'::jsonb,'雨天玻璃窗与模糊景色，适合“情绪低落、回忆”',NULL,NULL,'pending_asset'),
('CF120','自我反思','["自我反思", "雨天室内"]'::jsonb,'公园独自散步背影，适合“恢复、平静、疗愈”',NULL,NULL,'pending_asset'),
('CF121','自我反思','["自我反思", "散步背影"]'::jsonb,'单人窗边发呆，适合“内耗、迷茫、自我和解”',NULL,NULL,'pending_asset'),
('CF122','自我反思','["自我反思", "独处沉思"]'::jsonb,'空房间与一把椅子，适合“失落、留白、重新整理自己”',NULL,NULL,'pending_asset'),
('CF123','自我反思','["自我反思", "窗边发呆"]'::jsonb,'夜晚台灯与书桌，适合“深夜思考、情绪记录”',NULL,NULL,'pending_asset'),
('CF124','自我反思','["自我反思", "空房间"]'::jsonb,'雨天玻璃窗与模糊景色，适合“情绪低落、回忆”',NULL,NULL,'pending_asset'),
('CF125','自我反思','["自我反思", "夜晚台灯"]'::jsonb,'公园独自散步背影，适合“恢复、平静、疗愈”',NULL,NULL,'pending_asset'),
('CF126','迁移旅行','["迁移旅行", "人生选择", "机场出发"]'::jsonb,'机场候机与行李箱，适合“留学、搬迁、远行”',NULL,NULL,'pending_asset'),
('CF127','迁移旅行','["迁移旅行", "行李与道路"]'::jsonb,'火车站台与离别，适合“异地、出发、人生变化”',NULL,NULL,'pending_asset'),
('CF128','迁移旅行','["迁移旅行", "人生选择", "异地生活"]'::jsonb,'公路旅行与远山，适合“新开始、迁移、长期计划”',NULL,NULL,'pending_asset'),
('CF129','迁移旅行','["迁移旅行", "火车站"]'::jsonb,'陌生城市街景，适合“新生活、新环境”',NULL,NULL,'pending_asset'),
('CF130','迁移旅行','["迁移旅行", "人生选择", "旅途公路"]'::jsonb,'旅馆窗前或背包整理，适合“到达另一座城市”',NULL,NULL,'pending_asset'),
('CF131','迁移旅行','["迁移旅行", "陌生城市"]'::jsonb,'机场候机与行李箱，适合“留学、搬迁、远行”',NULL,NULL,'pending_asset'),
('CF132','迁移旅行','["迁移旅行", "人生选择", "机场出发"]'::jsonb,'火车站台与离别，适合“异地、出发、人生变化”',NULL,NULL,'pending_asset'),
('CF133','迁移旅行','["迁移旅行", "行李与道路"]'::jsonb,'公路旅行与远山，适合“新开始、迁移、长期计划”',NULL,NULL,'pending_asset'),
('CF134','迁移旅行','["迁移旅行", "人生选择", "异地生活"]'::jsonb,'陌生城市街景，适合“新生活、新环境”',NULL,NULL,'pending_asset'),
('CF135','迁移旅行','["迁移旅行", "火车站"]'::jsonb,'旅馆窗前或背包整理，适合“到达另一座城市”',NULL,NULL,'pending_asset'),
('CF136','通用留白','["通用留白", "职场发展", "自我反思", "极简桌面"]'::jsonb,'极简桌面与大面积空白墙面，适合任何标题覆盖',NULL,NULL,'pending_asset'),
('CF137','通用留白','["通用留白", "自然风景"]'::jsonb,'柔和窗帘与自然光，适合通用故事卡封面',NULL,NULL,'pending_asset'),
('CF138','通用留白','["通用留白", "职场发展", "抽象光影"]'::jsonb,'植物角落与木质家具，适合温暖治愈主题',NULL,NULL,'pending_asset'),
('CF139','通用留白','["通用留白", "自我反思", "空椅子"]'::jsonb,'抽象光影落在墙面上，适合通用留白与情绪过渡',NULL,NULL,'pending_asset'),
('CF140','通用留白','["通用留白", "职场发展", "窗帘与光"]'::jsonb,'安静风景与低饱和天空，适合“后来、然后呢”类标题',NULL,NULL,'pending_asset'),
('CF141','通用留白','["通用留白", "墙面留白"]'::jsonb,'空椅子、桌子或走廊，适合等待、回访、留白意味',NULL,NULL,'pending_asset'),
('CF142','通用留白','["通用留白", "职场发展", "自我反思", "植物角落"]'::jsonb,'极简桌面与大面积空白墙面，适合任何标题覆盖',NULL,NULL,'pending_asset'),
('CF143','通用留白','["通用留白", "极简桌面"]'::jsonb,'柔和窗帘与自然光，适合通用故事卡封面',NULL,NULL,'pending_asset'),
('CF144','通用留白','["通用留白", "职场发展", "自然风景"]'::jsonb,'植物角落与木质家具，适合温暖治愈主题',NULL,NULL,'pending_asset'),
('CF145','通用留白','["通用留白", "自我反思", "抽象光影"]'::jsonb,'抽象光影落在墙面上，适合通用留白与情绪过渡',NULL,NULL,'pending_asset'),
('CF146','通用留白','["通用留白", "职场发展", "空椅子"]'::jsonb,'安静风景与低饱和天空，适合“后来、然后呢”类标题',NULL,NULL,'pending_asset'),
('CF147','通用留白','["通用留白", "窗帘与光"]'::jsonb,'空椅子、桌子或走廊，适合等待、回访、留白意味',NULL,NULL,'pending_asset'),
('CF148','通用留白','["通用留白", "职场发展", "自我反思", "墙面留白"]'::jsonb,'极简桌面与大面积空白墙面，适合任何标题覆盖',NULL,NULL,'pending_asset'),
('CF149','通用留白','["通用留白", "植物角落"]'::jsonb,'柔和窗帘与自然光，适合通用故事卡封面',NULL,NULL,'pending_asset'),
('CF150','通用留白','["通用留白", "职场发展", "极简桌面"]'::jsonb,'植物角落与木质家具，适合温暖治愈主题',NULL,NULL,'pending_asset');
