import React, { useEffect, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {api,setToken,hasSession} from './api';
import './style.css';
import {OfficialData} from './OfficialData.jsx';
import {Management} from './Management.jsx';
import {DraftAssistant} from './DraftAssistant.jsx';
import {DraftEvidence} from './DraftEvidence.jsx';
import {MemoryMaterials} from './MemoryMaterials.jsx';
import {ZhihuAccount} from './ZhihuAccount.jsx';
import {SourceMaterials} from './SourceMaterials.jsx';
import {draftActions,interviewActions,poll} from './workflow.js';

function App(){
 const [answerVisibility,setAnswerVisibility]=useState('public');
 const [draftJobPending,setDraftJobPending]=useState(false);
 const [page,setPage]=useState('发现'),[user,setUser]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[items,setItems]=useState([]),[query,setQuery]=useState(''),[url,setUrl]=useState(''),[login,setLogin]=useState(''),[story,setStory]=useState(null),[memory,setMemory]=useState(null),[session,setSession]=useState(null),[messages,setMessages]=useState([]),[answer,setAnswer]=useState(''),[draft,setDraft]=useState(null),[caseId,setCaseId]=useState(''),[sourceId,setSourceId]=useState(''),[notice,setNotice]=useState(''),[savedStatements,setSavedStatements]=useState(''),[followup,setFollowup]=useState(null),[storyComments,setStoryComments]=useState(null);
 const draftState=draftActions(draft,savedStatements),interviewState=interviewActions(session,messages);
 function loadDraft(value){setDraft(value);setSavedStatements(JSON.stringify(value.statements));}
 useEffect(()=>{if(busy)return;
  if(page==='采访'&&session?.status==='active')return poll(()=>api('/interviews/'+session.id),d=>{setSession(d.session);setMessages(d.messages||[]);},e=>setError(e.message));
  if(page==='资料与记忆'&&memory?.status==='pending')return poll(()=>api('/me/memory'),setMemory,e=>setError(e.message));
 },[page,session?.id,session?.status,memory?.status,busy]);
 async function run(fn,message){setError('');setNotice('');setBusy(true);try{await fn();if(message)setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function enter(p){setPage(p);setItems([]);setNotice('');await run(async()=>{if(p==='发现'){const [stories,candidates]=await Promise.all([api('/stories'),hasSession()?api('/discovery/feed'):Promise.resolve({items:[]})]);setItems([...stories.items,...candidates.items]);}if(p==='我的关注'){const [stories,candidates]=await Promise.all([api('/me/following'),api('/discovery/following')]);setItems([...stories.items.filter(x=>!candidates.items.some(c=>c.linked_source_id===x.source_id)),...candidates.items]);}if(p==='通知')setItems((await api('/me/notifications')).items);if(p==='资料与记忆')setMemory(await api('/me/memory'));if(p==='作者工作台')setItems((await api('/me/workbench')).items);});}
 useEffect(()=>{enter('发现');},[]);
 async function identify(data){setToken(data.session_token);setUser(data.user);setLogin('');await enter('发现');}
 async function readInterview(id){const d=await api('/interviews/'+id);setSession(d.session);setMessages(d.messages||[]);setPage('采访');}
 async function actionInterview(action){try{await api(`/interviews/${session.id}/${action}`,'POST',{expected_version:session.revision});}catch(e){if(e.status===409){await readInterview(session.id);throw new Error('采访已有更新，请查看最新问题后再次操作。');}throw e;}await readInterview(session.id);}
 async function openStory(id){const d=await api('/stories/'+id);setStory(d.story);setSourceId(id);setStoryComments(null);setPage('内容');setStoryComments(await api(`/stories/${id}/comments`));}
 return <><header><a href="#" onClick={()=>enter('发现')}>然后呢？</a><span>让认真留下的回答，等到它的后来。</span><small>{user?`${user.display_name||'当前用户'} · ${user.role}`:'尚未登录'}</small></header><nav>{['发现','我的关注','作者工作台','通知','资料与记忆','账号',...(['author','admin','researcher'].includes(user?.role)?['提交资料']:[]),...(user?.role==='admin'?['官方数据']:[]),...(['admin','researcher'].includes(user?.role)?['回访管理']:[])].map(p=><button key={p} disabled={busy} onClick={()=>enter(p)}>{p}</button>)}</nav><main aria-busy={busy}>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">处理中…</p>}{notice&&<p role="status">{notice}</p>}
 {page==='回访管理'&&['admin','researcher'].includes(user?.role)&&<Management role={user.role}/>}
 {page==='官方数据'&&user?.role==='admin'&&<OfficialData/>}
 {page==='账号'&&<section><h1>进入然后呢？</h1><p>读者会话用于记录你关注的故事。作者可使用一次性登录凭证；站内登录后可查看知乎授权状态。</p><button disabled={busy} onClick={()=>run(async()=>identify(await api('/auth/readers','POST',{consent:{accepted:true,version:'v1'}})))}>同意建立读者会话并进入</button><label>一次性登录凭证<input type="password" value={login} onChange={e=>setLogin(e.target.value)}/></label><button disabled={busy} onClick={()=>run(async()=>identify(await api('/auth/sessions','POST',{login_token:login})))}>登录</button>{user&&<><button disabled={busy} onClick={()=>run(async()=>setUser((await api("/me")).user))}>刷新站内身份</button><ZhihuAccount onSignedIn={identify}/></>}{user&&<button onClick={()=>run(async()=>{await api('/auth/logout','POST');setToken('');setUser(null);})}>退出</button>}</section>}
 {page==='发现'&&<><h1>故事还在继续</h1><p>浏览本站内容，或通过知乎官方搜索发现值得回访的经历。</p><form onSubmit={e=>{e.preventDefault();run(async()=>setItems((await api('/discovery/search?q='+encodeURIComponent(query))).items));}}><input aria-label="搜索关键词" value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如：转行、毕业之后"/><button disabled={busy}>搜索知乎</button></form><form onSubmit={e=>{e.preventDefault();run(async()=>{const d=await api('/sources/resolve','POST',{url});setSourceId(d.source_id);setNotice(d.status==='pending_content'?'已登记链接，官方渠道暂未取得该帖正文。':'已取得官方摘要，等待作者核验与展示许可。');});}}><input aria-label="知乎链接" value={url} onChange={e=>setUrl(e.target.value)} placeholder="粘贴知乎回答或文章链接"/><button disabled={busy}>导入链接</button></form></>}
 {['发现','我的关注'].includes(page)&&<section>{!items.length&&!busy&&<p>这里暂时没有内容。</p>}{items.map((x,i)=><article key={x.source_id||x.url||i}><h2>{x.title||'尚未命名的故事'}</h2>{x.author_name&&<p>{x.author_name} · 官方摘要</p>}<p className="body">{x.text}</p>{x.source_id?<button onClick={()=>run(()=>openStory(x.source_id))}>查看故事</button>:<><p>资料范围：官方摘要，不代表完整原文。</p><details><summary>部分知乎评论</summary>{x.comments?.map((c,n)=><p key={n}>{c}</p>)}</details><a href={x.url} target="_blank" rel="noreferrer">在知乎查看原内容</a>{x.candidate_id&&<button disabled={busy} onClick={()=>run(async()=>{await api(`/discovery/candidates/${x.candidate_id}/interest`,'PUT',{active:!x.interested});setItems(current=>current.map(item=>item.candidate_id===x.candidate_id?{...item,interested:!x.interested}:item));},x.interested?'已取消关注。':'已关注这篇内容的后续，后台将整理已有回访材料。')}>{x.interested?'取消后续关注':'然后呢？关注后续'}</button>}{x.linked_source_id&&<button disabled={busy} onClick={()=>run(()=>openStory(x.linked_source_id))}>查看本站后续</button>}<button onClick={()=>{setUrl(x.url);}}>填入导入链接</button></>}</article>)}</section>}
 {page==='内容'&&story&&<article><h1>{story.title}</h1><p>{story.material_level==='exact_excerpt'?'原文片段':'材料摘要'} · {story.provenance==='test_fixture'?'测试材料':'来源材料'}</p><p className="body">{story.text}</p><button disabled={busy} onClick={()=>run(()=>api(`/stories/${sourceId}/interest`,'PUT',{active:true}),'已关注。有新的后来时，会在站内通知你。')}>然后呢？</button><button disabled={busy} onClick={()=>run(()=>api(`/stories/${sourceId}/interest`,'PUT',{active:false}),'已取消关注。')}>取消关注</button><details><summary>已同步的知乎评论</summary><p>{storyComments?.synced_at?'最近同步：'+storyComments.synced_at:'尚未通过官方同步取得评论。'} 附带回复不保证覆盖全部楼中楼。</p>{storyComments?.items.map(c=><article key={c.id}><p>{c.text}</p>{c.author_url&&<a href={c.author_url} target="_blank" rel="noreferrer">评论作者的知乎主页</a>}</article>)}</details>{story.published_followup&&<><h2>后来</h2>{story.published_followup.statements.map(x=><p key={x.id}>{x.text}</p>)}</>}</article>}
 {page==='通知'&&<><h1>更新通知</h1>{items.length===0&&<p>暂无更新。</p>}{items.map(x=><article key={x.id}><p>你关注的故事有了后来。</p><button onClick={()=>run(async()=>{await api(`/notifications/${x.id}/read`,'POST');const d=await api('/followups/'+x.followupVersionId);setFollowup(d);setPage('更新');})}>阅读更新</button></article>)}</>}
 {page==='更新'&&followup&&<article><h1>作者的后来</h1><p>由作者确认并在本站发布。</p>{followup.statements.map(x=><p key={x.id} className="body">{x.text}</p>)}<button onClick={()=>run(()=>openStory(followup.source_id))}>查看原故事</button></article>}
 {page==='提交资料'&&<SourceMaterials role={user?.role}/>} {page==='资料与记忆'&&<section><h1>用于提问的作者资料</h1><p>只使用你同意处理且已经核验归属的材料。不会把资料不足的部分补写成人物档案。</p><p>状态：{memory?.status||'尚未建立'}　更新：{memory?.updated_at||'暂无'}</p><button disabled={busy} onClick={()=>run(async()=>{await api('/me/memory/consent','PUT',{enabled:true});setMemory(await api('/me/memory'));})}>同意建立作者记忆</button><button disabled={busy} onClick={()=>run(async()=>{await api('/me/memory/refresh','POST');setMemory(await api('/me/memory'));})}>刷新资料</button><button disabled={busy} onClick={()=>run(async()=>{await api('/me/memory/consent','PUT',{enabled:false});setMemory(await api('/me/memory'));})}>撤销同意并删除记忆</button><MemoryMaterials materials={memory?.materials}/>{memory?.records.map(x=><article key={x.name}><p>{x.preference?'采访边界：':''}{x.content}</p><small>来源：{x.source_id}</small></article>)}</section>}
 {page==='作者工作台'&&<section><h1>写下后来</h1>{items.length===0&&<p>暂无可处理的回访。完成身份与内容核验后，回访会显示在这里。</p>}{items.map(x=><article key={x.id}><h2>{x.title||'回访'}</h2><p>{x.status}</p><button onClick={()=>{setCaseId(x.id);setSourceId(x.source_id);setPage('回访');}}>处理回访</button>{x.interview_id&&<button onClick={()=>run(()=>readInterview(x.interview_id))}>继续采访</button>}{x.draft_id&&<button onClick={()=>run(async()=>{loadDraft(await api('/drafts/'+x.draft_id));setPage('草稿');})}>查看草稿</button>}</article>)}<label>回访编号<input value={caseId} onChange={e=>setCaseId(e.target.value)}/></label><button onClick={()=>setPage('回访')}>打开指定回访</button></section>}
 {page==='回访'&&<section><h1>接受一次时间回访</h1><p>你可以拒绝，也可以在采访中跳过任何问题。</p><label>原内容编号<input value={sourceId} onChange={e=>setSourceId(e.target.value)}/></label>{[['private_interview','同意私有采访'],['external_model_processing','同意将资料交给模型处理'],['demo_public_display','同意在本站展示']].map(([purpose,label])=><button key={purpose} disabled={busy} onClick={()=>run(()=>api(`/sources/${sourceId}/consents`,'POST',{purpose,version:'v1'}),'已保存这项同意。')}>{label}</button>)}<div><button onClick={()=>run(()=>api(`/cases/${caseId}/decision`,'POST',{decision:'accept'}),'已接受回访，可以开始采访。')}>接受回访</button><button onClick={()=>run(()=>api(`/cases/${caseId}/decision`,'POST',{decision:'decline'}),'已拒绝本次回访。')}>拒绝回访</button><button disabled={busy} onClick={()=>run(async()=>{const d=await api(`/cases/${caseId}/interviews`,'POST',{mode:'ai',confirms_own_content:true,confirms_old_state:true});await readInterview(d.session.id);})}>确认是我的内容，开始采访</button></div></section>}
 {page==='采访'&&session&&<section><h1>聊聊你的后来</h1><p>状态：{session.status} · 已问 {session.questionsAsked} / 5</p>{messages.map(x=><article key={x.id}><strong>{x.role==='ai'?'回访问题':'你的回答'}</strong><p>{x.question||x.authorMessage||(x.skipped?'已跳过':'')}</p></article>)}<button disabled={busy} onClick={()=>run(()=>readInterview(session.id))}>刷新下一问</button>{session.mode==='manual'&&session.stopReason&&<p>AI 提问暂不可用，已保存的回答仍保留。可以继续手动补充，或重试 AI 提问。</p>}{interviewState.retry&&<button disabled={busy} onClick={()=>run(async()=>{await api(`/interviews/${session.id}/retry`,'POST',{expected_version:session.revision});await readInterview(session.id);})}>重试 AI 提问</button>}{interviewState.waiting&&<p role="status">回答已保存，正在准备下一问…</p>}<label>回答范围<select value={answerVisibility} onChange={e=>setAnswerVisibility(e.target.value)}><option value="public">可用于公开草稿（仍需确认发布）</option><option value="private">仅私有采访使用</option></select></label><label>你的回答<textarea value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button disabled={busy||!answer||!interviewState.answer} onClick={()=>run(async()=>{await api(`/interviews/${session.id}/messages`,'POST',{message:answer,visibility:answerVisibility,client_message_id:crypto.randomUUID(),expected_version:session.revision});setAnswer('');await readInterview(session.id);})}>保存回答</button><button disabled={busy||!interviewState.answer} onClick={()=>run(async()=>{await api(`/interviews/${session.id}/messages`,'POST',{skip:true,client_message_id:crypto.randomUUID(),expected_version:session.revision});await readInterview(session.id);})}>跳过</button>{['pause','resume','finish'].map((a,i)=><button key={a} disabled={busy||!interviewState[a]} onClick={()=>run(()=>actionInterview(a))}>{['暂停','继续','结束采访'][i]}</button>)}{session.status==='finished'&&<button disabled={busy} onClick={()=>run(async()=>{const d=await api(`/interviews/${session.id}/draft`,'POST');loadDraft(d);setPage('草稿');})}>整理草稿</button>}</section>}
 {page==='草稿'&&draft&&<section><h1>确认你的后来</h1><DraftAssistant key={draft.id} draft={draft} dirty={draftState.dirty} disabled={busy} onDraft={loadDraft} onPending={setDraftJobPending}/><DraftEvidence key={draft.id+':evidence'} draft={draft}/><p>状态：{draft.status} · 版本 {draft.version}</p>{draftState.dirty&&<p role="status">有未保存的修改。保存后才能确认并发布这段新内容。</p>}{draft.statements?.map((s,i)=><article key={s.id}><label>内容<textarea disabled={draftJobPending} value={s.text} onChange={e=>setDraft({...draft,statements:draft.statements.map((x,n)=>n===i?{...x,text:e.target.value}:x)})}/></label><label>内容范围<select disabled={draftJobPending} value={s.visibility} onChange={e=>setDraft({...draft,statements:draft.statements.map((x,n)=>n===i?{...x,visibility:e.target.value}:x)})}><option value="public">可用于公开草稿</option><option value="private">仅自己可见</option></select></label><button disabled={busy||draftJobPending||draft.statements.length<=1} onClick={()=>setDraft({...draft,statements:draft.statements.filter((_,n)=>n!==i)})}>从草稿移除此项</button><small>依据：{s.evidence_refs?.join('、')}</small></article>)}<button disabled={busy||draftJobPending||!draftState.save} onClick={()=>run(async()=>loadDraft(await api(`/drafts/${draft.id}`,'PATCH',{expected_version:draft.version,statements:draft.statements})),'修改已保存，请重新确认。')}>保存修改</button><button disabled={busy||draftJobPending||!draftState.confirm} onClick={()=>run(async()=>{await api(`/drafts/${draft.id}/confirm`,'POST',{content_hash:draft.contentHash,statement_ids:draft.statements.map(x=>x.id)});loadDraft(await api('/drafts/'+draft.id));},'已确认当前版本，可以发布。')}>确认全部内容</button><button disabled={busy||draftJobPending||!draftState.publish} onClick={()=>run(async()=>{await api(`/drafts/${draft.id}/publish`,'POST',{content_hash:draft.contentHash,confirms_publication:true});loadDraft(await api('/drafts/'+draft.id));},'已发布到本站。关注者将收到站内更新通知。')}>确认发布到本站</button><button disabled={busy||draftJobPending||!draftState.withdraw} onClick={()=>run(async()=>{await api(`/followups/${draft.id}/withdraw`,'POST',{reason:'作者在页面主动撤回'});loadDraft(await api('/drafts/'+draft.id));},'已撤回，读者不能继续读取该版本。')}>撤回发布</button></section>}
 </main><footer>内容由作者确认后在本站发布。测试材料会明确标记。</footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
