import { authorMemories } from '../../src/db/schema.js';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { eq } from 'drizzle-orm';
import { auth, createHarness, seedPublishedStory, seedUser, type Harness } from './helpers.js';
import { consents, followupCases, interests, notifications, sources, sourceSnapshots, followupVersions, outbox } from '../../src/db/schema.js';
import { runJob } from '../helpers/run-job.js';

describe('durable manual interview flow', () => {
  let h: Harness;
  beforeAll(async () => { h = await createHarness(); });
  afterAll(async () => { await h.close(); });
  it('falls back explicitly, saves answers idempotently, enforces ownership and resumes after app state reload', async () => {
    const author = await seedUser(h, 'author', 'test_fixture');
    const other = await seedUser(h, 'author', 'test_fixture');
    const story = await seedPublishedStory(h, { author: author.user, verifyAuthor: true });
    await h.ctx.db.update(followupCases).set({ status: 'accepted', publishedVersionId: null }).where(eq(followupCases.id, story.followupCase.id));
    const url = `/api/cases/${story.followupCase.id}/interviews`;
    const start = { mode: 'ai', confirms_own_content: true, confirms_old_state: true };
    expect((await h.app.inject({ method: 'POST', url, headers: auth(author.token), payload: start })).statusCode).toBe(422);
    await h.ctx.db.insert(consents).values({ userId: author.user.id, sourceId: story.source.id, purpose: 'private_interview' });
    const res = await h.app.inject({ method: 'POST', url, headers: auth(author.token), payload: start });
    expect(res.statusCode, res.body).toBe(200);
    const data = res.json().data;
    expect(data.fallback_reason).toBe('model_unconfigured');
    expect(data.session.mode).toBe('manual');
    const base = `/api/interviews/${data.session.id}`;
    expect((await h.app.inject({ method: 'GET', url: base, headers: auth(other.token) })).statusCode).toBe(403);
    const message = { message: '项目已完成。', visibility: 'public', client_message_id: 'answer-1', expected_version: 1 };
    const replies = await Promise.all(Array.from({ length: 3 }, () => h.app.inject({ method: 'POST', url: `${base}/messages`, headers: auth(author.token), payload: message })));
    for (const reply of replies) expect(reply.statusCode, reply.body).toBe(200);
    expect(new Set(replies.map(r => r.json().data.message.id)).size).toBe(1);
    expect((await h.app.inject({ method: 'POST', url: `${base}/messages`, headers: auth(author.token), payload: { ...message, message: 'changed' } })).statusCode).toBe(409);
    const pause = await h.app.inject({ method: 'POST', url: `${base}/pause`, headers: auth(author.token), payload: { expected_version: 2 } });
    expect(pause.statusCode, pause.body).toBe(200);
    expect((await h.app.inject({ method: 'POST', url: `${base}/messages`, headers: auth(author.token), payload: { ...message, client_message_id: 'answer-2', expected_version: 3 } })).statusCode).toBe(409);
    const read = await h.app.inject({ method: 'GET', url: base, headers: auth(author.token) });
    expect(read.json().data.messages).toHaveLength(1);
    expect(read.json().data.session.status).toBe('paused');
    expect((await h.app.inject({ method: 'POST', url: `${base}/resume`, headers: auth(author.token), payload: { expected_version: 3 } })).statusCode).toBe(200);
    const finishes = await Promise.all(Array.from({ length: 3 }, () => h.app.inject({ method: 'POST', url: `${base}/finish`, headers: auth(author.token), payload: { expected_version: 4 } })));
    for (const finish of finishes) {
      expect(finish.statusCode, finish.body).toBe(200);
      expect(finish.json().data.session.status).toBe('finished');
      expect(finish.json().data.pending_confirmation_items).toHaveLength(1);
    }
    expect(new Set(finishes.map(r => r.json().data.draft_id)).size).toBe(1);
    const draftResponse = await h.app.inject({ method: 'POST', url: `${base}/draft`, headers: auth(author.token) });
    expect(draftResponse.statusCode, draftResponse.body).toBe(200);
    const draft = draftResponse.json().data;
    expect(draft.id).toBe(finishes[0]!.json().data.draft_id);
    const draftUrl = `/api/drafts/${draft.id}`;
    const publish = { content_hash: draft.contentHash, confirms_publication: true };
    expect((await h.app.inject({ method: 'POST', url: `${draftUrl}/publish`, headers: auth(author.token), payload: publish })).statusCode).toBe(409);
    await h.ctx.db.insert(authorMemories).values({userId:author.user.id,enabled:false});
    const confirmed = await h.app.inject({ method: 'POST', url: `${draftUrl}/confirm`, headers: auth(author.token), payload: { content_hash: draft.contentHash, statement_ids: draft.statements.map((s: { id: string }) => s.id) } });
    expect(confirmed.statusCode, confirmed.body).toBe(200);
    const [memoryBeforeReplay]=await h.ctx.db.select().from(authorMemories).where(eq(authorMemories.userId,author.user.id));
    const replay=await h.app.inject({method:'POST',url:`${draftUrl}/confirm`,headers:auth(author.token),payload:{content_hash:draft.contentHash,statement_ids:draft.statements.map((s:{id:string})=>s.id)}});
    expect(replay.statusCode).toBe(200);
    const [memoryAfterReplay]=await h.ctx.db.select().from(authorMemories).where(eq(authorMemories.userId,author.user.id));
    expect(memoryAfterReplay!.generation).toBe(memoryBeforeReplay!.generation);
    const [awaitingReview] = await h.ctx.db.update(followupCases).set({ reviewerRequired: true }).where(eq(followupCases.id, story.followupCase.id)).returning();
    expect((await h.app.inject({ method: 'POST', url: `${draftUrl}/publish`, headers: auth(author.token), payload: publish })).statusCode).toBe(409);
    const reviewer = await seedUser(h, 'admin', 'test_fixture');
    const review = await h.app.inject({ method: 'POST', url: `/api/cases/${story.followupCase.id}/review`, headers: auth(reviewer.token), payload: {
      expected_version: awaitingReview!.updatedAt.toISOString(), snapshot_hash: story.snapshot.contentHash, decision: 'eligible', reason_code: 'source_checked', evidence_ref: 'evidence://test_fixture/author-case-review', confirms_source_and_safety_review: true,
    } });
    expect(review.statusCode, review.body).toBe(200);
    expect(review.json().data.status).toBe('draft');
    const reader = await seedUser(h, 'reader', 'test_fixture');
    const cancelledReader = await seedUser(h, 'reader', 'test_fixture');
    const lateReader = await seedUser(h, 'reader', 'test_fixture');
    await h.ctx.db.insert(interests).values([reader, cancelledReader].map(r => ({ sourceId: story.source.id, readerKey: r.user.id, cohort: 'test_fixture', excluded: true })));
    const publications = await Promise.all(Array.from({ length: 3 }, () => h.app.inject({ method: 'POST', url: `${draftUrl}/publish`, headers: auth(author.token), payload: publish })));
    for (const reply of publications) expect(reply.statusCode, reply.body).toBe(200);
    expect(publications.filter(r => !r.json().data.deduped)).toHaveLength(1);
    await h.ctx.db.update(interests).set({ active: false }).where(eq(interests.readerKey, cancelledReader.user.id));
    await h.ctx.db.insert(interests).values({ sourceId: story.source.id, readerKey: lateReader.user.id, cohort: 'test_fixture', excluded: true });
    await runJob(h.moduleCtx, 'followup.notify');
    const notices = await h.ctx.db.select().from(notifications).where(eq(notifications.followupVersionId, draft.id));
    expect(notices.map(n => n.readerKey)).toEqual([reader.user.id]);
    const ownNotifications = await h.app.inject({ url: '/api/me/notifications', headers: auth(reader.token) });
    expect(ownNotifications.statusCode).toBe(200);
    expect(ownNotifications.json().data.items.map((n: { readerKey: string }) => n.readerKey)).toEqual([reader.user.id]);
    expect((await h.app.inject({ url: '/api/me/notifications', headers: auth(lateReader.token) })).json().data.items).toEqual([]);
    await h.moduleCtx.jobs.enqueue({ kind: 'followup.notify', payload: { source_id: story.source.id, case_id: story.followupCase.id, version_id: draft.id } });
    await runJob(h.moduleCtx, 'followup.notify');
    expect(await h.ctx.db.select().from(notifications).where(eq(notifications.followupVersionId, draft.id))).toHaveLength(1);
    expect((await h.app.inject({ method: 'GET', url: `/api/followups/${draft.id}` })).json().data.statements[0].text).toBe('项目已完成。');
    const edited = await h.app.inject({ method: 'PATCH', url: draftUrl, headers: auth(author.token), payload: { expected_version: draft.version, statements: [{ ...draft.statements[0], text: '后来又修改了。' }] } });
    expect(edited.statusCode, edited.body).toBe(200);
    const next = edited.json().data;
    expect((await h.app.inject({ method: 'GET', url: `/api/followups/${draft.id}` })).statusCode).toBe(200);
    expect((await h.app.inject({ method: 'POST', url: `/api/drafts/${next.id}/publish`, headers: auth(author.token), payload: { content_hash: draft.contentHash, confirms_publication: true } })).statusCode).toBe(409);
    expect((await h.app.inject({ method: 'POST', url: `/api/followups/${draft.id}/withdraw`, headers: auth(author.token) })).statusCode).toBe(200);
    const withdrawn = await h.app.inject({ method: 'GET', url: `/api/followups/${draft.id}` });
    expect(withdrawn.statusCode).toBe(410);
    expect(withdrawn.body).not.toContain('项目已完成');
    const deleted = await h.app.inject({ method: 'DELETE', url: `/api/sources/${story.source.id}`, headers: auth(author.token) });
    expect(deleted.statusCode, deleted.body).toBe(202);
    expect((await h.app.inject({ method: 'GET', url: `/api/sources/${story.source.id}`, headers: auth(author.token) })).statusCode).toBe(404);
    await runJob(h.moduleCtx, 'source.delete');
    expect(await h.ctx.db.select().from(sources).where(eq(sources.id, story.source.id))).toHaveLength(0);
    expect(await h.ctx.db.select().from(sourceSnapshots).where(eq(sourceSnapshots.sourceId, story.source.id))).toHaveLength(0);
    expect(await h.ctx.db.select().from(followupVersions).where(eq(followupVersions.caseId, story.followupCase.id))).toHaveLength(0);
    expect(await h.ctx.db.select().from(outbox).where(eq(outbox.dedupeKey, draft.id))).toHaveLength(0);
    const receipt = await h.app.inject({ method: 'GET', url: `/api/deletions/${deleted.json().data.deletion_id}`, headers: auth(author.token) });
    expect(receipt.json().data.status).toBe('succeeded');
  });
  it('finishes a skipped-only interview without inventing a draft and permits retry', async () => {
    const author = await seedUser(h, 'author', 'test_fixture');
    const story = await seedPublishedStory(h, { author: author.user, verifyAuthor: true });
    await h.ctx.db.update(followupCases).set({ status: 'accepted', publishedVersionId: null }).where(eq(followupCases.id, story.followupCase.id));
    await h.ctx.db.insert(consents).values({ userId: author.user.id, sourceId: story.source.id, purpose: 'private_interview' });
    const start = await h.app.inject({ method: 'POST', url: `/api/cases/${story.followupCase.id}/interviews`, headers: auth(author.token), payload: { mode: 'manual', confirms_own_content: true, confirms_old_state: true } });
    const base = `/api/interviews/${start.json().data.session.id}`;
    const skipped = await h.app.inject({ method: 'POST', url: `${base}/messages`, headers: auth(author.token), payload: { skip: true, client_message_id: 'skip1', expected_version: 1 } });
    expect(skipped.statusCode, skipped.body).toBe(200);
    for (let attempt = 0; attempt < 2; attempt++) {
      const finished = await h.app.inject({ method: 'POST', url: `${base}/finish`, headers: auth(author.token), payload: { expected_version: 2 } });
      expect(finished.statusCode, finished.body).toBe(200);
      expect(finished.json().data).toMatchObject({ draft_id: null, pending_confirmation_items: [], draft_unavailable_reason: 'no_author_answers' });
    }
    expect(await h.ctx.db.select().from(followupVersions).where(eq(followupVersions.interviewId, start.json().data.session.id))).toHaveLength(0);
  });
});
