import {afterAll,beforeAll,afterEach,it,expect,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {createHarness,seedUser,auth,type Harness} from './helpers.js';
import {sessions,zhihuAccounts,zhihuOAuthAttempts,users} from '../../src/db/schema.js';
import {createOAuthAttempt,consumeOAuthAttempt} from '../../src/modules/zhihu/oauth-attempts.js';
import {bindOAuthAccount,readOAuthToken,disconnectOAuthAccount} from '../../src/modules/zhihu/oauth-accounts.js';
import {runJob} from '../helpers/run-job.js';
import {authorVerifications,consents,authorMemories,sources} from '../../src/db/schema.js';
import {authorizedMaterials} from '../../src/modules/memory/service.js';
let h:Harness;
const key='ab'.repeat(32),token={access_token:'fiction-token-only',expires_in:3600};
beforeAll(async()=>{h=await createHarness();});
afterAll(async()=>{await h.close();});
afterEach(()=>vi.unstubAllGlobals());
async function attempt(){const a=await seedUser(h,'reader');const [s]=await h.ctx.db.select().from(sessions).where(eq(sessions.userId,a.user.id));const start=await createOAuthAttempt(h.ctx.db,s!.id);const claim=await consumeOAuthAttempt(h.ctx.db,start.state,start.browserProof);return {...a,...claim};}
it('stores ciphertext only, completes once, enforces expiry and disconnects pending callbacks',async()=>{
 const a=await attempt(),now=new Date();
 await bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'123',fullname:'虚构账号'},token,key,now);
 const [stored]=await h.ctx.db.select().from(zhihuAccounts).where(eq(zhihuAccounts.userId,a.user.id));
 expect(JSON.stringify(stored)).not.toContain(token.access_token);
 expect(await readOAuthToken(h.ctx.db,a.user.id,key)).toBe(token.access_token);
 await expect(readOAuthToken(h.ctx.db,a.user.id,key,new Date(now.getTime()+3600000))).rejects.toThrow();
 await expect(bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'123'},token,key)).rejects.toThrow();
 await createOAuthAttempt(h.ctx.db,a.sessionId);
 await disconnectOAuthAccount(h.ctx.db,a.sessionId);
 await expect(readOAuthToken(h.ctx.db,a.user.id,key)).rejects.toThrow();
 expect(await h.ctx.db.select().from(zhihuOAuthAttempts).where(eq(zhihuOAuthAttempts.sessionId,a.sessionId))).toHaveLength(0);
 const [revoked]=await h.ctx.db.select().from(zhihuAccounts).where(eq(zhihuAccounts.userId,a.user.id));expect(revoked!.tokenCiphertext).toBeNull();
});
it('serializes competing identity claims without merging equal display names or changing roles',async()=>{
 const a=await attempt(),b=await attempt();
 const results=await Promise.allSettled([a,b].map(x=>bindOAuthAccount(h.ctx.db,x.attemptId,{uid:'456',fullname:'同名'},token,key)));
 expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);
 expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);
 const [u]=await h.ctx.db.select().from(users).where(eq(users.id,a.user.id));expect(u!.role).toBe('reader');
});
it('rolls back failed encryption and rejects session revocation between exchange and binding',async()=>{
 const a=await attempt();
 await expect(bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'789'},token,'invalid')).rejects.toThrow();
 expect(await h.ctx.db.select().from(zhihuAccounts).where(eq(zhihuAccounts.userId,a.user.id))).toHaveLength(0);
 await h.ctx.db.update(sessions).set({revokedAt:new Date()}).where(eq(sessions.id,a.sessionId));
 await expect(bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'789'},token,key)).rejects.toThrow();
});
it('runs the HTTP start/callback/status/disconnect flow using a simulated official provider',async()=>{
 Object.assign(h.ctx.env,{ZHIHU_APP_ID:'fixture-app',ZHIHU_APP_KEY:'fixture-key',ZHIHU_REDIRECT_URI:'https://example.test/api/auth/zhihu/callback',ZHIHU_TOKEN_ENCRYPTION_KEY:key,ZHIHU_OAUTH_STATE_VERIFIED:true});
 const a=await seedUser(h,'reader');
 const started=await h.app.inject({method:'POST',url:'/api/auth/zhihu/start',headers:auth(a.token),payload:{}});
 expect(started.statusCode).toBe(200);
 const url=new URL(started.json().data.authorization_url),state=url.searchParams.get('state');
 const cookie=String(started.headers['set-cookie']).split(';')[0]!;
 expect(String(started.headers['set-cookie'])).toContain('HttpOnly; Secure; SameSite=Lax');
 const transport=vi.fn<typeof fetch>().mockResolvedValueOnce(new Response(JSON.stringify({...token,token_type:'Bearer'}))).mockResolvedValueOnce(new Response('{"uid":"999","fullname":"虚构 OAuth 作者"}'));
 vi.stubGlobal('fetch',transport);
 const callback=`/api/auth/zhihu/callback?state=${state}&authorization_code=fiction-code`;
 const result=await h.app.inject({url:callback,headers:{cookie}});
 expect(result.statusCode).toBe(200);expect(result.body).not.toContain(token.access_token);
 expect((await h.app.inject({url:callback,headers:{cookie}})).statusCode).toBe(403);
 expect(transport).toHaveBeenCalledTimes(2);
 const finish={method:'POST' as const,url:'/api/auth/zhihu/finish',headers:auth(a.token),payload:{attempt_id:started.json().data.attempt_id}};
 const signed=await h.app.inject(finish);expect(signed.statusCode).toBe(200);expect(signed.json().data).toMatchObject({ready:true,user:{id:a.user.id}});
 expect((await h.app.inject(finish)).statusCode).toBe(409);
 const newcomer=await seedUser(h,'reader');
 const restart=await h.app.inject({method:'POST',url:'/api/auth/zhihu/start',headers:auth(newcomer.token),payload:{}});
 const newState=new URL(restart.json().data.authorization_url).searchParams.get('state');
 transport.mockResolvedValueOnce(new Response(JSON.stringify({...token,token_type:'Bearer'}))).mockResolvedValueOnce(new Response('{"uid":"999"}'));
 expect((await h.app.inject({url:`/api/auth/zhihu/callback?state=${newState}&code=fiction-again`,headers:{cookie:String(restart.headers['set-cookie']).split(';')[0]!}})).statusCode).toBe(200);
 const returnFinish={method:'POST' as const,url:'/api/auth/zhihu/finish',payload:{attempt_id:restart.json().data.attempt_id}};
 expect((await h.app.inject({...returnFinish,headers:auth(a.token)})).statusCode).toBe(409);
 const restored=await h.app.inject({...returnFinish,headers:auth(newcomer.token)});
 expect(restored.json().data.user.id).toBe(a.user.id);
 expect((await h.app.inject({url:'/api/me',headers:auth(restored.json().data.session_token)})).json().data.user.id).toBe(a.user.id);
 expect((await h.app.inject({url:'/api/me/zhihu',headers:auth(a.token)})).json().data.authorized).toBe(true);
 expect((await h.app.inject({method:'DELETE',url:'/api/me/zhihu',headers:auth(a.token)})).statusCode).toBe(200);
 expect((await h.app.inject({url:'/api/me/zhihu',headers:auth(a.token)})).json().data.authorized).toBe(false);
});

it('syncs official own summaries only after consent, verifies ownership, dedupes and stops using revoked material',async()=>{
 const a=await attempt();
 await bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'101010'},token,key);
 Object.assign(h.ctx.env,{ZHIHU_ACCESS_SECRET:'fixture-secret',ZHIHU_TOKEN_ENCRYPTION_KEY:key});
 const official=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({Code:0,Data:{Items:[{ContentType:'answer',Url:'https://www.zhihu.com/question/20/answer/30',Title:'虚构摘要',Summary:'虚构经历：学习八个月后转行。',CreatedAt:1}],Paging:{IsEnd:true}}})));
 vi.stubGlobal('fetch',official);
 expect((await h.app.inject({method:'POST',url:'/api/me/zhihu/sync',headers:auth(a.token),payload:{accept_material_processing:false}})).statusCode).toBe(400);
 const start=await h.app.inject({method:'POST',url:'/api/me/zhihu/sync',headers:auth(a.token),payload:{accept_material_processing:true}});
 expect(start.statusCode).toBe(200);
 const repeat=await h.app.inject({method:'POST',url:'/api/me/zhihu/sync',headers:auth(a.token),payload:{accept_material_processing:true}});
 expect(repeat.json().data.job_id).toBe(start.json().data.job_id);
 const result=await runJob(h.moduleCtx,'zhihu.author.sync');
 expect(result?.data?.imported).toBe(1);
 const [verification]=await h.ctx.db.select().from(authorVerifications).where(eq(authorVerifications.userId,a.user.id));
 expect(verification).toMatchObject({method:'oauth',status:'verified'});
 expect(await authorizedMaterials(h.moduleCtx,a.user.id)).toHaveLength(1);
 const [u]=await h.ctx.db.select().from(users).where(eq(users.id,a.user.id));expect(u!.role).toBe('author');
 const materials=await h.ctx.db.select().from(consents).where(eq(consents.userId,a.user.id));expect(materials.map(x=>x.purpose).sort()).toEqual(['external_model_processing','private_interview']);
 await h.app.inject({url:'/api/me/zhihu',headers:auth(a.token)});expect(official).toHaveBeenCalledTimes(1);
 await h.app.inject({method:'DELETE',url:'/api/me/zhihu',headers:auth(a.token)});
 expect(await authorizedMaterials(h.moduleCtx,a.user.id)).toHaveLength(0);
 const [memory]=await h.ctx.db.select().from(authorMemories).where(eq(authorMemories.userId,a.user.id));expect(memory!.records).toEqual([]);
 expect(await h.ctx.db.select().from(sources).where(eq(sources.id,verification!.sourceId))).toHaveLength(1);
});

it('cannot resurrect author memory when consent is disabled while a sync is queued',async()=>{
 const a=await attempt();await bindOAuthAccount(h.ctx.db,a.attemptId,{uid:'202020'},token,key);
 Object.assign(h.ctx.env,{ZHIHU_ACCESS_SECRET:'fixture-secret',ZHIHU_TOKEN_ENCRYPTION_KEY:key});
 await h.app.inject({method:'POST',url:'/api/me/zhihu/sync',headers:auth(a.token),payload:{accept_material_processing:true}});
 await h.app.inject({method:'PUT',url:'/api/me/memory/consent',headers:auth(a.token),payload:{enabled:false}});
 vi.stubGlobal('fetch',vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({Code:0,Data:{Items:[],Paging:{IsEnd:true}}}))));
 await expect(runJob(h.moduleCtx,'zhihu.author.sync')).rejects.toThrow('authorization changed');
 const [memory]=await h.ctx.db.select().from(authorMemories).where(eq(authorMemories.userId,a.user.id));expect(memory!.enabled).toBe(false);
});
